package registry

// Checks is the conformance inventory in execution order.
var Checks = []Check{
	{Name: "conformance-meta", Implementation: "checkConformanceMeta", Tier: Dev, Meta: true, Subject: SubjectKitRoot},
	{Name: "conformance-canary-families", Implementation: "checkConformanceCanaryFamilies", Tier: Dev, Meta: true, Subject: SubjectKitRoot},
	{Name: "kit-compliance", Implementation: "checkKitCompliance", Tier: Dev, Subject: SubjectKitRoot, Inputs: InputCatchAll},
	{Name: "canary-fixture-compliance", Implementation: "checkCanaryFixtureCompliance", Tier: Dev, Subject: SubjectRoot, Inputs: InputCatchAll},
	{Name: "load-validity-metadata", Implementation: "checkLoadValidityMetadata", Tier: Dev, Subject: SubjectRoot, Inputs: InputCatchAll},
	{Name: "skills-index-command-adapters", Implementation: "checkSkillsIndexAndCommandAdapters", Tier: Dev, Subject: SubjectRoot, Inputs: InputCatchAll},
	{Name: "docs-currency-workflow", Implementation: "checkDocsCurrencyAndWorkflow", Tier: Dev, Subject: SubjectRootAndKitRoot, Inputs: InputCatchAll},
	{Name: "gate-entry-contract", Implementation: "checkGateEntryContract", Tier: Dev, Subject: SubjectRoot, Inputs: InputGateEntry},
	{Name: "ordinary-build-census", Implementation: "checkOrdinaryBuildCensus", Tier: Dev, Subject: SubjectKitRoot, Inputs: InputCatchAll},
	{Name: "offline-smoke-proof", Implementation: "checkOfflineSmokeProof", Tier: Dev, Subject: SubjectRoot, Inputs: InputOfflineSmoke},
	{Name: "handoff-shape-single-source", Implementation: "checkHandoffShape", Tier: Dev, Subject: SubjectRoot, Inputs: InputCatchAll},
	{Name: "harness-prefix-single-source", Implementation: "checkHarnessPrefix", Tier: Dev, Subject: SubjectRoot, Inputs: InputGoSource},
	{Name: "package-shipped-surface", Implementation: "checkPackageShippedSurface", Tier: Dev, Subject: SubjectRoot, Inputs: InputCatchAll},
	{Name: "line-routing", Implementation: "checkLineRouting", Tier: Dev, Subject: SubjectRoot, Inputs: InputCatchAll},
	{Name: "package-core-guard", Implementation: "checkPackageCoreAndGuards", Tier: Dev, Subject: SubjectRoot, Inputs: InputCatchAll},
	{Name: "release-evidence-probe", Implementation: "checkReleaseEvidenceProbe", Tier: Ship, Subject: SubjectRoot, Inputs: InputCatchAll},
	{Name: "bench-sh-routes", Implementation: "checkBenchShRoutes", Tier: Dev, Subject: SubjectRoot, Inputs: InputBenchRoutes},
	{Name: "default-branch-single-source", Implementation: "checkDefaultBranchSingleSource", Tier: Dev, Subject: SubjectRoot, Inputs: InputGoSource},
	{Name: "data-handling-derivation", Implementation: "checkDataHandlingDerivation", Tier: Dev, Subject: SubjectRoot, Inputs: InputGoAndDataHandling},
	{Name: "single-control-escaper", Implementation: "checkSingleControlEscaper", Tier: Dev, Subject: SubjectRoot, Inputs: InputGoSource},
	{Name: "bounds-policy", Implementation: "checkBoundsPolicy", Tier: Dev, Subject: SubjectRoot, Inputs: InputCatchAll},
	{Name: "marker-wait-deadlines", Implementation: "checkMarkerWaitDeadlines", Tier: Dev, Subject: SubjectRoot, Inputs: InputGoSource},
	{Name: "canonical-path-owner", Implementation: "checkCanonicalPathOwner", Tier: Dev, Subject: SubjectRoot, Inputs: InputGoSource},
	{Name: "published-executable-path", Implementation: "checkPublishedExecutablePath", Tier: Dev, Subject: SubjectRoot, Inputs: InputCatchAll},
	{Name: "go-build-vcs", Implementation: "checkGoBuildVCS", Tier: Dev, Subject: SubjectRoot, Inputs: InputCatchAll},
	{Name: "git-plumbing-owner", Implementation: "checkGitPlumbingOwner", Tier: Dev, Subject: SubjectRoot, Inputs: InputGoSource},
	{Name: "cancel-signal-registrations", Implementation: "checkCancelSignalRegistrations", Tier: Dev, Subject: SubjectRoot, Inputs: InputGoSource},
	{Name: "wait-deadline-literals", Implementation: "checkWaitDeadlineLiterals", Tier: Dev, Subject: SubjectRoot, Inputs: InputGoSource},
	{Name: "subcommand-routing", Implementation: "checkSubcommandRouting", Tier: Dev, Subject: SubjectRoot, Inputs: InputGoSource},
	{Name: "axi-query-registry", Implementation: "checkAXIQueryRegistry", Tier: Dev, Subject: SubjectRoot, Inputs: InputCatchAll},
	{Name: "skip-ownership", Implementation: "checkSkipOwnership", Tier: Dev, Subject: SubjectRoot, Inputs: InputGoSource},
	{Name: "decision-map-integrity", Implementation: "ValidateDecisionMapTree", Tier: Dev, Subject: SubjectRoot, Inputs: InputDecisionDocuments},
	{Name: "injected-port-registry", Implementation: "checkInjectedPortRegistry", Tier: Dev, Subject: SubjectRoot, Inputs: InputGoSource},
	{Name: "guidance-prose-budgets", Implementation: "checkGuidanceProseBudgets", Tier: Dev, Subject: SubjectRoot, Inputs: InputBenchkitProfile},
	{Name: "skill-description-budgets", Implementation: "checkSkillDescriptionBudgets", Tier: Dev, Subject: SubjectRoot, Inputs: InputBenchkitProfile},
	{Name: "profile-lane-table", Implementation: "checkProfileLaneTable", Tier: Dev, Subject: SubjectRoot, Inputs: InputBenchkitProfile},
	{Name: "roadmap-detail-integrity", Implementation: "ValidateRoadmapTree", Tier: Dev, Subject: SubjectRoot, Inputs: InputRoadmapBoard},
	{Name: "structure-accept-currency", Implementation: "ValidateAcceptGrants", Tier: Dev, Subject: SubjectRoot, Inputs: InputCatchAll},
	{Name: "retro-improvement-markers", Implementation: "ValidateImprovementMarkers", Tier: Dev, Subject: SubjectRoot, Inputs: InputCaptureRetros},
	{Name: "row-next-grammar", Implementation: "checkRowNextGrammar", Tier: Dev, Subject: SubjectRoot, Inputs: InputCatchAll},
	{Name: "prose-mechanics", Implementation: "checkProseMechanics", Tier: Dev, Subject: SubjectRoot, Inputs: InputCatchAll},
	{Name: "entry-point-parity", Implementation: "checkEntryPointParity", Tier: Dev, Subject: SubjectRoot, Inputs: InputCatchAll},
	{Name: "harness-record", Implementation: "checkHarnessRecord", Tier: Dev, Subject: SubjectRoot, Inputs: InputCatchAll},
	{Name: "ticket-grammar", Implementation: "checkTicketGrammar", Tier: Dev, Subject: SubjectRoot, Inputs: InputCatchAll},
	{Name: "claude-agent-definitions", Implementation: "checkClaudeAgentDefinitions", Tier: Dev, Subject: SubjectRoot, Inputs: InputCatchAll},
}
