package anchors

// This file holds the decision-map anchor rows — the two phase commands, the rendered
// template, and the README description of the split shape — plus the CONTEXT.md
// map-term glossary rows, which moved here for the line budget of registry_data.go.
// A decision map is an index beside its topic folder, and each decision lives in one
// ticket file the index links.
var decisionMapAnchors = []Anchor{
	{Group: AfterImplementSpec, File: ".agents/commands/bench-shape-idea.md", Kind: Require, Section: "", Needle: "Read one ready decision map's `## Sources` block before the first write.", Diagnostic: ".agents/commands/bench-shape-idea.md dropped the ready-map Sources read before the first decision-map write"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-shape-idea.md", Kind: Require, Section: "", Needle: "Run `bench maps` and `bench gate-prose` on the first skeleton.", Diagnostic: ".agents/commands/bench-shape-idea.md dropped the bench-maps and bench-gate-prose checks on the first decision-map skeleton"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-shape-idea.md", Kind: Forbid, Section: "", Needle: "prose preflight", Diagnostic: ".agents/commands/bench-shape-idea.md writes an unnamed prose check; `bench gate-prose` is the one handle"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-shape-idea.md", Kind: Forbid, Section: "", Needle: "decisions/assets/", Diagnostic: ".agents/commands/bench-shape-idea.md keeps the flat decisions/assets/ path; a map-owned asset stays under the topic folder"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-write-spec.md", Kind: Forbid, Section: "", Needle: "decisions/assets/", Diagnostic: ".agents/commands/bench-write-spec.md keeps the flat decisions/assets/ path; a map-owned asset moves with the topic folder"},
	{Group: AfterImplementSpec, File: "internal/maps/schema.go", Kind: Require, Section: "", Needle: "decisions/<topic>/assets/", Diagnostic: "internal/maps/schema.go dropped the decisions/<topic>/assets/ path for a map-owned asset from the decision-map template"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-write-spec.md", Kind: Require, Section: "", Needle: "Move the topic folder, its tickets and assets included, into the spec's decisions folder as one unit.", Diagnostic: ".agents/commands/bench-write-spec.md dropped the compile-time decision-map move"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-write-spec.md", Kind: Require, Section: "", Needle: "Whole-folder retirement removes the compiled topic folders, their tickets and assets included.", Diagnostic: ".agents/commands/bench-write-spec.md dropped the whole-folder compiled decision-map retirement"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-shape-idea.md", Kind: Require, Section: "", Needle: "The map is an index: it lists the decisions made and links the ticket that holds each one.", Diagnostic: ".agents/commands/bench-shape-idea.md dropped the index role of the map file"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-shape-idea.md", Kind: Require, Section: "", Needle: "A decision ticket is one file under the map's tickets folder, named by its number.", Diagnostic: ".agents/commands/bench-shape-idea.md dropped the one-file-per-decision-ticket rule"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-shape-idea.md", Kind: Require, Section: "", Needle: "The answer lives only in the ticket file.", Diagnostic: ".agents/commands/bench-shape-idea.md dropped the single home of a decision answer"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-shape-idea.md", Kind: Require, Section: "", Needle: "Decisions so far holds one gist line per resolved ticket, with a link to its file.", Diagnostic: ".agents/commands/bench-shape-idea.md dropped the gist-line contents of Decisions so far"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-shape-idea.md", Kind: Require, Section: "", Needle: "Notes holds the domain, the skills a session consults, and the standing preferences of that map.", Diagnostic: ".agents/commands/bench-shape-idea.md dropped the contents of the map's Notes section"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-shape-idea.md", Kind: Require, Section: "", Needle: "The shaping worktree lease is the claim, and no owner field enters a ticket.", Diagnostic: ".agents/commands/bench-shape-idea.md dropped the worktree-lease claim or admitted an owner field into a ticket"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-shape-idea.md", Kind: Require, Section: "", Needle: "Name a ticket by its title, with its number beside it.", Diagnostic: ".agents/commands/bench-shape-idea.md dropped the title-first naming rule for a decision ticket"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-shape-idea.md", Kind: Require, Section: "", Needle: "A grill recommendation that asserts current-code behavior names the evidence read in the current session.", Diagnostic: ".agents/commands/bench-shape-idea.md dropped the current-session evidence rule for a grill recommendation"},
	{Group: AfterSpecAuthorization, File: "README.md", Kind: Require, Section: "", Needle: "each decision lives in one ticket file under the map's tickets folder", Diagnostic: "README.md dropped the split decision-map shape; each decision lives in one ticket file under the map's tickets folder"},
	{Group: AfterSpecAuthorization, File: "CONTEXT.md", Kind: Require, Section: "", Needle: "Not \"map\", not \"traceability matrix\" — coverage map.", Diagnostic: "CONTEXT.md dropped the coverage-map glossary entry with the Avoid list that names the bare word map"},
	{Group: AfterSpecAuthorization, File: "CONTEXT.md", Kind: Require, Section: "", Needle: "Not \"PRD\", not \"design doc\", not \"map\" — decision map.", Diagnostic: "CONTEXT.md decision-map entry dropped the Avoid list that names the bare word map"},
	{Group: AfterSpecAuthorization, File: "CONTEXT.md", Kind: Require, Section: "", Needle: "Not \"census\", not \"consumer audit\" — reader sweep.", Diagnostic: "CONTEXT.md dropped the reader-sweep glossary entry with the Avoid list that reserves census"},
	{Group: AfterSpecAuthorization, File: "CONTEXT.md", Kind: Require, Section: "", Needle: "one line in Decisions so far that links a resolved decision ticket", Diagnostic: "CONTEXT.md dropped the gist glossary entry that names the Decisions so far line linking a resolved decision ticket"},
}
