package anchors

// ft311ReviewDispatchAnchors pin the review phase's native-dispatch authority, the
// prepared evidence that phase consumes, and the triage input contract beside it. The
// Require rows keep each rule present. The Forbid rows keep the retired same-family
// CLI and inline-axis routes out. One diagnostic prefix lets the conformance owner
// enumerate this set without a second registry.
var ft311ReviewDispatchAnchors = []Anchor{
	{Group: AfterImplementSpec, File: ".agents/commands/bench-review-implementation.md", Kind: Require, Needle: "By default, an authorized review dispatches every prepared axis through the native agent surface without a second approval. Each axis uses a different independent session, an isolated read-only venue, and its own source derivation. A version 2 completion plan can set `execution.review_mode` to `unified` as the sole exception. One independent session re-derives Standards, Spec, and Coverage separately, then reports each axis separately.", Diagnostic: "prepared review dispatch: bench-review-implementation.md dropped default axis isolation or the explicit unified exception"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-review-implementation.md", Kind: Require, Needle: "Prepare the shared evidence once with `bench preflight review <slug> --charge --base <b> --source-tip <t>`. Supply the same frozen base that preflight used. The command publishes one immutable artifact and prints its identity. Retrieve every byte with `bench preflight evidence <id>` and each exact successor command it prints. The metadata names one charge row for each axis, and it binds the diff, consumers, and coverage captures to their frozen sources.", Diagnostic: "prepared review dispatch: bench-review-implementation.md does not consume the prepared shared evidence; the phase collects the diff, consumers, and coverage a second time"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-review-implementation.md", Kind: Require, Needle: "Take the consumer tables and their citation row from the shared evidence's `consumers` identity. Do not run a second `bench consumers --changed` collection for the same frozen pair.", Diagnostic: "prepared review dispatch: bench-review-implementation.md walks the blast from a second consumer collection instead of the prepared shared evidence"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-delegate/references/delegation-discipline.md", Kind: Require, Needle: "The CLI owns routine deterministic failure projection. A triage delegate never repeats it.", Diagnostic: "prepared review dispatch: delegation-discipline.md dropped the CLI's ownership of routine deterministic failure projection"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-delegate/references/delegation-discipline.md", Kind: Require, Needle: "The coordinator gives triage the failed command, the selected checks, the actual execution evidence, the findings, and the frozen source.", Diagnostic: "prepared review dispatch: delegation-discipline.md dropped the triage input contract of failed command, selected checks, execution evidence, findings, and frozen source"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-review-implementation.md", Kind: Require, Needle: "Each review round dispatches a fresh session for each axis. The coordinator keeps the manifest, the metadata page, and the current binding, and it gives the evidence identity to each axis.", Diagnostic: "narrow review axis: bench-review-implementation.md dropped the fresh axis session for each round or the coordinator's evidence hand-off"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-review-implementation.md", Kind: Require, Needle: "A narrow axis runs `bench preflight evidence <id> --check-current` one time, to bind the artifact to the assignment and the source pair. The axis reads the delta through one `git diff` of the frozen pair. It reads the spec rows, the tickets, the standards, and the surrounding code with targeted reads. It returns a bounded report with one line for each finding. A resumed axis session keeps every earlier stream in its context, so the phase does not resume an axis for a later round.", Diagnostic: "narrow review axis: bench-review-implementation.md dropped the single binding, the one-diff read, the targeted reads, the bounded return, or the no-resume rule of a narrow axis"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-review-implementation.md", Kind: Require, Needle: "This narrow axis shape is provisional. Each narrow round records what each axis read and what it found. One full-retrieval control review of the same diff decides whether the shape becomes the permanent rule.", Diagnostic: "narrow review axis: bench-review-implementation.md dropped the provisional status or the full-retrieval control review of the narrow axis shape"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-review-implementation.md", Kind: Require, Needle: "A confirming round reads only the repair delta, and its charge names the folds to confirm.", Diagnostic: "narrow review axis: bench-review-implementation.md lets a confirming round read more than the repair delta or drop its named folds"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-review-implementation.md", Kind: Require, Needle: "Collect every axis return before you accept a finding. A missing or failed axis return leaves the review incomplete. It is never a clean finding set.", Diagnostic: "prepared review dispatch: bench-review-implementation.md lets a missing or failed axis return stand as a clean finding set"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-review-implementation.md", Kind: Require, Needle: "Native availability is a fact of the active session. A compiled harness record is not runtime proof of a native agent surface.", Diagnostic: "prepared review dispatch: bench-review-implementation.md accepts a compiled harness record as runtime proof of a native surface"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-review-implementation.md", Kind: Require, Needle: "When the native tool is unavailable, or when the reviewer prohibits delegation, preserve the prepared charges and stop dispatch. Then emit a capable-harness handoff. The handoff names the repository, the assignment, the frozen pair, the charge inputs, the destination harness, and that harness's exact native continuation command.", Diagnostic: "prepared review dispatch: bench-review-implementation.md dropped charge preservation, the dispatch stop, or one named input of the capable-harness handoff"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-review-implementation.md", Kind: Require, Needle: "A historical review and a spec-less review keep their existing preparation entry points under this same native authority rule.", Diagnostic: "prepared review dispatch: bench-review-implementation.md exempts a historical or spec-less review from the native authority rule"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-review-implementation.md", Kind: Forbid, Needle: "run the same axes inline", Diagnostic: "prepared review dispatch: bench-review-implementation.md retains the inline-axis fallback"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-delegate/references/cross-harness-reviewers.md", Kind: Require, Needle: "A harness without a native subagent surface takes the capable-harness handoff in `.agents/commands/bench-review-implementation.md`, and it substitutes no same-family CLI.", Diagnostic: "prepared review dispatch: cross-harness-reviewers.md dropped the capable-harness handoff route for a missing native surface"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-delegate/references/cross-harness-reviewers.md", Kind: Forbid, Needle: "falls back to its own family's CLI", Diagnostic: "prepared review dispatch: cross-harness-reviewers.md retains the own-family CLI fallback"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-delegate/SKILL.md", Kind: Require, Needle: "Without a native surface, hand off to a capable harness.", Diagnostic: "prepared review dispatch: craft-delegate dropped the capable-harness handoff route for a missing native surface"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-spec/SKILL.md", Kind: RequireInSection, Section: "Template", Needle: "Line: <resolved implementation model id> / <starting effort>.", Diagnostic: "retained workflow: craft-spec dropped the one implementation-line template"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-spec/SKILL.md", Kind: RequireInSection, Section: "Template", Needle: "Implementation-line reason: <hardest material chunk, spec precision, seam uncertainty, and test strength>.", Diagnostic: "retained workflow: craft-spec dropped the implementation-line reason factors"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-spec/SKILL.md", Kind: RequireInSection, Section: "Template", Needle: "Harder chunks: <chunk IDs or none>.", Diagnostic: "retained workflow: craft-spec dropped the harder-chunk annotation"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/SKILL.md", Kind: Require, Needle: "A Codex mid implementation sends each axis to the Codex top binding.", Diagnostic: "retained workflow: craft-line dropped the Codex mid-to-top review branch"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/SKILL.md", Kind: Require, Needle: "Every other implementation sends each axis to the invoking harness's mid binding.", Diagnostic: "retained workflow: craft-line dropped the default mid review branch"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/SKILL.md", Kind: Require, Needle: "A different implementation model, or a session beyond the planned ticket authors, requires user direction. The ticket author can adjust effort in its own session and reports the change.", Diagnostic: "retained workflow: craft-line dropped the user-directed model-switch boundary"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-review-implementation.md", Kind: Require, Needle: "Resolve every axis through `craft-line`'s conditional review line from the implementation model.", Diagnostic: "retained workflow: review phase dropped the conditional review-line reference"},
	{Group: AfterImplementSpec, File: "projects/benchkit.md", Kind: Require, Needle: "conditional review line in `craft-line`", Diagnostic: "retained workflow: project profile dropped the conditional review-line reference"},
	{Group: AfterImplementSpec, File: ".bench/BENCH.md", Kind: Require, Needle: "Every spec-backed build gives each ticket a fresh author session on the declared line, with or without `--full`, and a tier move asks me first.", Diagnostic: "fresh ticket author: operating guide dropped the fresh author session for each ticket on the declared line"},
	{Group: AfterImplementSpec, File: ".bench/BENCH.md", Kind: Require, Needle: "The build records its authors in the version 2 delegate plan with an author limit of 1.", Diagnostic: "fresh ticket author: operating guide dropped the limit-1 version 2 delegate plan"},
	{Group: AfterImplementSpec, File: ".bench/BENCH.md", Kind: Forbid, Needle: "The retained implementation session writes production changes, tests, probes, and repairs.", Diagnostic: "fresh ticket author: operating guide restored the retained implementation session"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-review-implementation.md", Kind: Require, Needle: "Accepted findings go to a fresh repair author under `.bench/BENCH.md`'s repair rule.", Diagnostic: "fresh ticket author: review phase dropped the fresh repair author for accepted findings"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-review-implementation.md", Kind: Forbid, Needle: "Accepted findings return to the retained `/bench-implement-spec` session.", Diagnostic: "fresh ticket author: review phase restored the finding return to the retained session"},
	{Group: AfterImplementSpec, File: "docs/field-guide.html", Kind: Forbid, Needle: "the approved implementation line retains one author through production changes, tests, probes, repairs, and chunk reviews.", Diagnostic: "fresh ticket author: field guide restored the one retained author on the approved implementation line"},
	{Group: AfterImplementSpec, File: ".bench/BENCH.md", Kind: Require, Needle: "An implementation chunk is one coherent behavior outcome with acceptance rows, tests, and a review checkpoint.", Diagnostic: "retained workflow: operating guide dropped chunk outcome and review checkpoint"},
	{Group: AfterImplementSpec, File: ".bench/BENCH.md", Kind: Require, Needle: "A ticket remains a serial green commit checkpoint.", Diagnostic: "retained workflow: operating guide dropped serial ticket checkpoint"},
	{Group: AfterImplementSpec, File: ".bench/BENCH.md", Kind: Require, Needle: "After a chunk's ticket commits, freeze its delta and run Standards, Spec, and Coverage against the whole approved spec before starting its successor.", Diagnostic: "retained workflow: operating guide allows advancement before three-axis chunk review"},
	{Group: AfterImplementSpec, File: ".bench/BENCH.md", Kind: Require, Needle: "After the last chunk, the orchestrator reconciles the final acceptance and integration.", Diagnostic: "fresh ticket author: operating guide dropped the orchestrator's final reconciliation"},
	{Group: AfterImplementSpec, File: ".bench/BENCH.md", Kind: Forbid, Needle: "After the last chunk, the retained author reconciles overall acceptance and integration.", Diagnostic: "fresh ticket author: operating guide restored the retained author's final reconciliation"},
	{Group: AfterImplementSpec, File: ".bench/BENCH.md", Kind: Forbid, Needle: "Return findings to the retained author and obtain current repair coverage.", Diagnostic: "fresh ticket author: operating guide restored the finding return to the retained author"},
	{Group: AfterImplementSpec, File: ".bench/BENCH.md", Kind: Require, Needle: "Repeat delegated review only for a later delta or a cross-chunk concern that invalidates prior evidence.", Diagnostic: "retained workflow: operating guide restored routine final full review"},
	{Group: AfterImplementSpec, File: ".bench/BENCH.md", Kind: Require, Needle: "A brief read-only diagnostic consultation can inspect evidence, but it receives no implementation or repair assignment.", Diagnostic: "retained workflow: operating guide dropped diagnostic-only consultation boundary"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-drain.md", Kind: Require, Needle: "If tracked changes remain, the retained drain session authors the complete tracked batch.", Diagnostic: "retained workflow: drain restored delegated batch authorship"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-review-implementation.md", Kind: Require, Needle: "Review action requires a narrow axis read: act only after this session reads the frozen delta and the targeted sources of its axis. An axis does not retrieve every evidence page. `bench preflight evidence <id> --verify` is the separate artifact-integrity check.", Diagnostic: "bounded review action: bench-review-implementation.md permits review action without a narrow axis read"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-review-implementation.md", Kind: Require, Needle: "Review action requires available required context: a retrieval receipt, a terminal cursor, or another axis's read never replaces the sources this session reads.", Diagnostic: "bounded review action: bench-review-implementation.md permits review action without available required context"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-review-implementation.md", Kind: Require, Needle: "Review action requires a current-action binding: act only after `bench preflight evidence <id> --check-current` binds the artifact to the current assignment and source pair.", Diagnostic: "bounded review action: bench-review-implementation.md permits review action without a current binding"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-review-implementation.md", Kind: Require, Needle: "Review action requires reviewer approval, which a generated charge, a staged artifact, or a verified artifact never supplies.", Diagnostic: "bounded review action: bench-review-implementation.md permits review action without reviewer approval"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-review-implementation.md", Kind: Require, Needle: "Review action requires the complete task supplement, which this session writes. The supplement names the axis, the model, the effort, and the frozen pair, and verified evidence never supplies it.", Diagnostic: "bounded review action: bench-review-implementation.md permits review action without the complete task supplement"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-review-implementation.md", Kind: Forbid, Needle: "bench preflight review <slug> --charge --base <b> --source-tip <t> --full", Diagnostic: "bounded review action: bench-review-implementation.md re-advertises the retired review full charge form"},

	// The consumer-context rows below state the same two rules over the review reader.
	// The coordinator is the retained consumer here, and each axis is a fresh one.
	{Group: AfterImplementSpec, File: ".agents/commands/bench-review-implementation.md", Kind: Require, Needle: "The coordinator reuses exact available source bytes only after the new manifest verifies their membership, role, and requiredness. A matching body digest alone authorizes no reuse.", Diagnostic: "consumer context: bench-review-implementation.md permits reuse without verified membership, role, and requiredness"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-review-implementation.md", Kind: Require, Needle: "A fresh axis runs its own retrieval from the trusted evidence identity. A transferred final cursor and another axis's receipt deliver no byte to it.", Diagnostic: "consumer context: bench-review-implementation.md permits another axis's receipt or a final cursor to replace fresh required context"},

	// The native-handoff row keeps the destination harness able to resume the same review.
	// The trusted identity and the exact retrieval command travel together, because the
	// originating checkout path names no evidence and authorizes no retrieval.
	{Group: AfterImplementSpec, File: ".agents/commands/bench-review-implementation.md", Kind: Require, Needle: "The handoff carries the trusted expected evidence identity and the exact `bench preflight evidence <id>` retrieval command, never the originating checkout path.", Diagnostic: "native handoff: bench-review-implementation.md drops the trusted evidence identity or the exact retrieval command from the capable-harness handoff"},
}
