package anchors

var ticketSlicingAnchors = []Anchor{
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-tickets/SKILL.md", Kind: RequireInSection, Section: "Draft the breakdown", Needle: "Before ticket lock, run a source-clause pass and an executable-route pass.", Diagnostic: "ticket slicing: verification passes must precede ticket lock"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-tickets/SKILL.md", Kind: RequireInSection, Section: "Draft the breakdown", Needle: "Assign each applicable source clause to a ticket or an explicit scope cut.", Diagnostic: "ticket slicing: source clauses need a ticket or explicit scope cut"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-tickets/SKILL.md", Kind: RequireInSection, Section: "Draft the breakdown", Needle: "Trace each claimed operation through its executable owner, using the [map-discipline proof rules](../bench-craft-spec/references/map-discipline.md#before-the-map-locks).", Diagnostic: "ticket slicing: executable routes need their owner and canonical proof rules"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-tickets/SKILL.md", Kind: RequireInSection, Section: "Write one file per ticket", Needle: "A ticket names every relocation destination in `Writes:`, including destinations for snapshots and registry rows.", Diagnostic: "ticket slicing: relocation destinations belong in Writes"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-tickets/SKILL.md", Kind: RequireInSection, Section: "Draft the breakdown", Needle: "A ticket that creates a seam its sibling tickets consume is its own review chunk, and that chunk stays small. Its chunk review closes before any consumer ticket starts. A seam the implementation introduces counts the same as a seam the spec declares.", Diagnostic: "ticket slicing: a seam-creating ticket takes its own review chunk and closes review before its consumers"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-tickets/SKILL.md", Kind: RequireInSection, Section: "Write one file per ticket", Needle: "Before you lock a `Writes:` line, read [the slicing checks](references/slicing-checks.md), which list every `Writes:` rule that the parser and build preflight enforce.", Diagnostic: "ticket slicing: craft-tickets must point to the slicing checks"},
	{Group: AfterImplementSpec, File: slicingChecks, Kind: RequireInSection, Section: "Enforced rules", Needle: "A `Writes:` entry for an anchored guidance path, or a directory above one, names every anchor registry file that names it, test files included.", Diagnostic: "ticket slicing: the anchor closure rule is enforced"},
	{Group: AfterImplementSpec, File: slicingChecks, Kind: RequireInSection, Section: "Enforced rules", Needle: "The spec's ownership fence equals the union of the ticket `Writes:` paths, less the review pickup and every path under the spec folder or `capture`.", Diagnostic: "ticket slicing: the fence equals the Writes union"},
	{Group: AfterImplementSpec, File: slicingChecks, Kind: RequireInSection, Section: "Slicing rules", Needle: "A lane-check ticket proves its check through the real lane over a composed tree.", Diagnostic: "ticket slicing: a lane check needs the real lane"},
	{Group: AfterImplementSpec, File: slicingChecks, Kind: RequireInSection, Section: "Slicing rules", Needle: "A posture change that reds a fixture helper makes the slicer list every call site of that helper before the map locks.", Diagnostic: "ticket slicing: a fixture helper posture change lists every call site"},
	{Group: AfterImplementSpec, File: slicingChecks, Kind: RequireInSection, Section: "Slicing rules", Needle: "A combined behavior row belongs to the ticket that completes its final consumer.", Diagnostic: "ticket slicing: a combined row belongs to its final consumer"},
	{Group: AfterImplementSpec, File: slicingChecks, Kind: RequireInSection, Section: "Slicing rules", Needle: "A retirement pass gives each sentence that grants the retired behavior its own forbid row and red-capable check.", Diagnostic: "ticket slicing: each retired grant needs its own forbid row"},
	{Group: AfterImplementSpec, File: slicingChecks, Kind: RequireInSection, Section: "Slicing rules", Needle: "A cited verifier row names the exact checks it performed.", Diagnostic: "ticket slicing: a verifier row names its exact checks"},
	{Group: AfterImplementSpec, File: slicingChecks, Kind: RequireInSection, Section: "Slicing rules", Needle: "The slicer runs `bench preflight build <slug>` after each change to a ticket or an acceptance row.", Diagnostic: "ticket slicing: build preflight reruns after each ticket or acceptance row change"},
	{Group: AfterImplementSpec, File: slicingChecks, Kind: RequireInSection, Section: "Slicing rules", Needle: "The spec goes to review, to sign-off, and to its landing only on a green preflight of its current ticket graph.", Diagnostic: "ticket slicing: review, sign-off, and the landing wait for a green build preflight"},
	{Group: AfterImplementSpec, File: slicingChecks, Kind: RequireInSection, Section: "Slicing rules", Needle: "Each acceptance claim names an available producer and an executable check at its ticket checkpoint.", Diagnostic: "ticket slicing: each claim names its producer and check at its checkpoint"},
	{Group: AfterImplementSpec, File: slicingChecks, Kind: RequireInSection, Section: "Slicing rules", Needle: "A ticket that preserves or moves a ref names a check for each of the head, the tip, and the checked-out-ref shapes.", Diagnostic: "ticket slicing: a ref move checks every ref shape"},
	{Group: AfterImplementSpec, File: slicingChecks, Kind: RequireInSection, Section: "Slicing rules", Needle: "A rule for one member of an enumerated family goes on its declaration row, and `Writes:` names the declaration table and its dispatch test.", Diagnostic: "ticket slicing: a per-member rule fences its family declaration table and dispatch test"},
	{Group: AfterImplementSpec, File: slicingChecks, Kind: RequireInSection, Section: "Slicing rules", Needle: "A ticket that adds a second caller of another package's private rule names that package in `Writes:`, so one exported rule serves both callers.", Diagnostic: "ticket slicing: a second caller of a private rule fences the rule's owner package"},
	{Group: AfterImplementSpec, File: mapDiscipline, Kind: RequireInSection, Section: "Before the map locks", Needle: "A spec that adds an invariant check sweeps every input constructor of that check.", Diagnostic: "map discipline: a new invariant check sweeps its input constructors"},
	{Group: AfterImplementSpec, File: mapDiscipline, Kind: RequireInSection, Section: "Before the map locks", Needle: "Each input constructor satisfies the new invariant, or its file joins a ticket `Writes:` line.", Diagnostic: "map discipline: each input constructor satisfies the invariant or joins Writes"},
	{Group: AfterImplementSpec, File: mapDiscipline, Kind: RequireInSection, Section: "Before the map locks", Needle: "A spec that adds or removes a preflight row names every file that asserts the row count or the row list.", Diagnostic: "map discipline: a preflight row change names every row-count reader"},
	{Group: AfterImplementSpec, File: mapDiscipline, Kind: RequireInSection, Section: "Before the map locks", Needle: "A spec that changes the output of a fixture builder names every test that asserts or rewrites that output.", Diagnostic: "map discipline: a fixture builder change names every output reader"},
	{Group: AfterImplementSpec, File: mapDiscipline, Kind: RequireInSection, Section: "Per row", Needle: "The seam cell cites that function as `` `<path>_test.go` (`<Name>`) ``, so `bench coverage --check` and build preflight resolve the name against the tree.", Diagnostic: "map discipline: an existing test seam cites its function in the resolvable form"},
}

// slicingChecks is the craft-tickets reference that states the enforced Writes: rules
// and the slicing rules no check enforces.
const slicingChecks = ".agents/skills/bench-craft-tickets/references/slicing-checks.md"

// mapDiscipline is the craft-spec reference that holds the reader-sweep rules.
const mapDiscipline = ".agents/skills/bench-craft-spec/references/map-discipline.md"
