package anchors

var ticketSlicingAnchors = []Anchor{
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-tickets/SKILL.md", Kind: RequireInSection, Section: "Draft the breakdown", Needle: "Before ticket lock, run a source-clause pass and an executable-route pass.", Diagnostic: "ticket slicing: verification passes must precede ticket lock"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-tickets/SKILL.md", Kind: RequireInSection, Section: "Draft the breakdown", Needle: "Assign each applicable source clause to a ticket or an explicit scope cut.", Diagnostic: "ticket slicing: source clauses need a ticket or explicit scope cut"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-tickets/SKILL.md", Kind: RequireInSection, Section: "Draft the breakdown", Needle: "Trace each claimed operation through its executable owner, using the [map-discipline proof rules](../bench-craft-spec/references/map-discipline.md#before-the-map-locks).", Diagnostic: "ticket slicing: executable routes need their owner and canonical proof rules"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-tickets/SKILL.md", Kind: RequireInSection, Section: "Write one file per ticket", Needle: "A ticket names every relocation destination in `Writes:`, including destinations for snapshots and registry rows.", Diagnostic: "ticket slicing: relocation destinations belong in Writes"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-tickets/SKILL.md", Kind: RequireInSection, Section: "Draft the breakdown", Needle: "A ticket that creates a seam its sibling tickets consume is its own review chunk, and that chunk stays small. Its chunk review closes before any consumer ticket starts. A seam the implementation introduces counts the same as a seam the spec declares.", Diagnostic: "ticket slicing: a seam-creating ticket takes its own review chunk and closes review before its consumers"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-tickets/SKILL.md", Kind: RequireInSection, Section: "Write one file per ticket", Needle: "Before you lock a `Writes:` line, read [the slicing checks](references/slicing-checks.md), which list every `Writes:` rule that the parser and build preflight enforce.", Diagnostic: "ticket slicing: craft-tickets must point to the slicing checks"},
	{Group: AfterImplementSpec, File: slicingChecks, Kind: RequireInSection, Section: "Enforced rules", Needle: "A `Writes:` entry that names an anchored guidance path, or a directory above one, also names every anchor registry file that names that path.", Diagnostic: "ticket slicing: the anchor closure rule is enforced"},
	{Group: AfterImplementSpec, File: slicingChecks, Kind: RequireInSection, Section: "Enforced rules", Needle: "The spec's ownership fence equals the union of the ticket `Writes:` paths, less the review pickup and every path under the spec folder or `capture`.", Diagnostic: "ticket slicing: the fence equals the Writes union"},
	{Group: AfterImplementSpec, File: slicingChecks, Kind: RequireInSection, Section: "Slicing rules", Needle: "A lane-check ticket proves its check through the real lane over a composed tree.", Diagnostic: "ticket slicing: a lane check needs the real lane"},
	{Group: AfterImplementSpec, File: slicingChecks, Kind: RequireInSection, Section: "Slicing rules", Needle: "A posture change that reds a fixture helper makes the slicer list every call site of that helper before the map locks.", Diagnostic: "ticket slicing: a fixture helper posture change lists every call site"},
	{Group: AfterImplementSpec, File: slicingChecks, Kind: RequireInSection, Section: "Slicing rules", Needle: "A combined behavior row belongs to the ticket that completes its final consumer.", Diagnostic: "ticket slicing: a combined row belongs to its final consumer"},
	{Group: AfterImplementSpec, File: slicingChecks, Kind: RequireInSection, Section: "Slicing rules", Needle: "A retirement pass gives each sentence that grants the retired behavior its own forbid row and red-capable check.", Diagnostic: "ticket slicing: each retired grant needs its own forbid row"},
	{Group: AfterImplementSpec, File: slicingChecks, Kind: RequireInSection, Section: "Slicing rules", Needle: "A cited verifier row names the exact checks it performed.", Diagnostic: "ticket slicing: a verifier row names its exact checks"},
	{Group: AfterImplementSpec, File: slicingChecks, Kind: RequireInSection, Section: "Slicing rules", Needle: "The slicer runs build preflight again after each fence change and before review.", Diagnostic: "ticket slicing: build preflight reruns after each fence change"},
}

// slicingChecks is the craft-tickets reference that states the enforced Writes: rules
// and the slicing rules no check enforces.
const slicingChecks = ".agents/skills/bench-craft-tickets/references/slicing-checks.md"
