package anchors

import (
	"strings"

	"github.com/gibbonmi/bench/internal/retros"
)

// retainedWorkflowAnchors is the whole retained-workflow family: the default
// contract below, the opt-in delegated exception that follows it, the
// lane-and-landing split, the retro capture route, the declared author line, and
// the fact owners that the guides point to.
// The registry reads this one name, so its groups evaluate together.
var retainedWorkflowAnchors = append(append(append(append(append(append([]Anchor{}, defaultWorkflowAnchors...), delegatedWorkflowAnchors...), laneAndLandingAnchors...), retroCaptureAnchors...), declaredLineAnchors...), factOwnerAnchors...)

// Each owner sentence below has one Require row at its owner. The Forbid row that keeps
// a copy out of a former copy site reads the same constant.
const (
	// handoffSectionRule is the reference's owner sentence for the handoff verb.
	handoffSectionRule = "`bench handoff` rewrites only the calling worktree's assignment section."
	// censusSignalAccount is the reference's owner sentence for the census signal.
	censusSignalAccount = "The `census` signal counts raw calls per assignment from `$BENCH_HOME/census/<repo-key>/`."
	// greenRunGateOutput opens the reference's green-run gate output sentence.
	greenRunGateOutput = "A green run prints one `phases[N]{phase,verdict,elapsed_ms}` table"
	// redRunGateOutput opens the reference's red-run gate output sentence.
	redRunGateOutput = "A red run prints one `failures[N]{phase,line}` table"
	// skillLinkRule is the Claude README's owner sentence for the skill links.
	skillLinkRule = "`.claude/skills/` links every `.agents/skills/` skill that has no same-named command."
)

// factOwnerAnchors pin each guide's pointer to the file that holds its fact.
// Require rows pin the owner sentences: the command registry for the plumbing
// subcommands, the reference for how the pieces fit, the skills index, the gate
// output, the handoff verb, the plan version, and the one internal verb that a
// session runs, and the Claude README for the skill links. Require rows also pin
// the pointers that replace each copy. Forbid rows keep out the retired copies,
// the reference's verb grammar, the false skill-link claims, the any-branch
// commit claim, and the light path's gate-then-commit wording.
var factOwnerAnchors = []Anchor{
	{Group: AfterImplementSpec, File: ".bench/BENCH.md", Kind: Forbid, Needle: "live in `.bench/BENCH-reference.md`", Diagnostic: "fact owner: operating guide restored the reference as the home of the plumbing subcommands"},
	{Group: AfterImplementSpec, File: ".bench/BENCH.md", Kind: Require, Needle: "The command registry owns the plumbing subcommands that hooks and adapters drive.", Diagnostic: "fact owner: operating guide dropped the command registry as the owner of the plumbing subcommands"},
	{Group: AfterImplementSpec, File: ".bench/BENCH.md", Kind: Forbid, Needle: "gate and commit on green", Diagnostic: "fact owner: operating guide light path restored the gate-then-commit wording"},
	{Group: AfterImplementSpec, File: "AGENTS.md", Kind: Forbid, Needle: "the four invariants, how the pieces fit", Diagnostic: "fact owner: working agreement restored how the pieces fit as a shared platform rule"},
	{Group: AfterImplementSpec, File: "AGENTS.md", Kind: Forbid, Needle: "the communication rules, and the skills index", Diagnostic: "fact owner: working agreement restored the skills index as a shared platform rule"},
	{Group: AfterImplementSpec, File: "AGENTS.md", Kind: Require, Needle: "`.bench/BENCH-reference.md` holds how the pieces fit and the skills index.", Diagnostic: "fact owner: working agreement dropped the reference as the holder of how the pieces fit and the skills index"},
	{Group: AfterImplementSpec, File: "AGENTS.md", Kind: Require, Needle: "`.bench/BENCH-reference.md` states how `bench handoff` writes the handoff file.", Diagnostic: "fact owner: working agreement dropped its pointer to the reference for the handoff verb behavior"},
	{Group: AfterImplementSpec, File: "AGENTS.md", Kind: Forbid, Needle: "The primary checkout owns the `main` section.", Diagnostic: "fact owner: working agreement restored its copy of the handoff main-section owner"},
	{Group: AfterImplementSpec, File: "AGENTS.md", Kind: Forbid, Needle: "The verb keeps a non-empty Next command.", Diagnostic: "fact owner: working agreement restored its copy of the handoff Next-command rule"},
	{Group: AfterImplementSpec, File: "AGENTS.md", Kind: Forbid, Needle: "refuses a State that pins a commit outside the tip's ancestry", Diagnostic: "fact owner: working agreement restored its copy of the handoff State ancestry refusal"},
	{Group: AfterImplementSpec, File: "AGENTS.md", Kind: Forbid, Needle: "Give the drafted State to `bench handoff --state-file <path>`.", Diagnostic: "fact owner: working agreement restored its copy of the handoff state-file route"},
	{Group: AfterImplementSpec, File: ".bench/BENCH-reference.md", Kind: RequireInSection, Section: "Plumbing subcommands", Needle: "`bench gate-prose` is the one internal verb that a session runs directly; Command Notes gives its forms.", Diagnostic: "fact owner: reference Plumbing subcommands dropped bench gate-prose as the one internal verb that a session runs"},
	{Group: AfterSpecAuthorization, File: ".bench/BENCH-reference.md", Kind: Require, Needle: greenRunGateOutput, Diagnostic: ".bench/BENCH-reference.md dropped the green-run gate output shape"},
	{Group: AfterImplementSpec, File: "projects/benchkit.md", Kind: Require, Needle: "`.bench/BENCH-reference.md` owns the bounded gate output account.", Diagnostic: "fact owner: project profile dropped its pointer to the reference for the gate output"},
	{Group: AfterImplementSpec, File: "projects/benchkit.md", Kind: Forbid, Needle: redRunGateOutput, Diagnostic: "fact owner: project profile restored its copy of the red-run gate output that the reference owns"},
	{Group: AfterImplementSpec, File: "projects/benchkit.md", Kind: Forbid, Needle: "one `capability-skips` line", Diagnostic: "fact owner: project profile restored its copy of the green-run capability-skips line that the reference owns"},
	{Group: AfterImplementSpec, File: "projects/benchkit.md", Kind: Forbid, Needle: "`phases: N/N green`", Diagnostic: "fact owner: project profile restored its copy of the collapsed green-run row that the reference owns"},
	{Group: AfterImplementSpec, File: "projects/benchkit.md", Kind: Forbid, Needle: "one more row names the file that holds the complete stream", Diagnostic: "fact owner: project profile restored its copy of the red-run stream row that the reference owns"},
	{Group: AfterImplementSpec, File: "projects/benchkit.md", Kind: Forbid, Needle: "The complete phase stream goes to `.logs/gate-<run>.out`", Diagnostic: "fact owner: project profile restored its copy of the gate stream log that the reference owns"},
	{Group: AfterImplementSpec, File: "projects/benchkit.md", Kind: Forbid, Needle: "`.logs/gate-<run>.jsonl` progress log", Diagnostic: "fact owner: project profile restored its copy of the gate progress log that the reference owns"},
	{Group: AfterImplementSpec, File: "projects/benchkit.md", Kind: Forbid, Needle: "`bench commit` works on any branch", Diagnostic: "fact owner: project profile restored the false claim that bench commit works on any branch"},
	{Group: AfterSpecAuthorization, File: ".bench/BENCH-reference.md", Kind: Require, Needle: handoffSectionRule, Diagnostic: ".bench/BENCH-reference.md dropped the handoff section rule; bench handoff rewrites only the calling worktree's assignment section"},
	{Group: AfterImplementSpec, File: ".bench/BENCH-reference.md", Kind: Forbid, Needle: "`bench handoff [--harness <name>]", Diagnostic: "fact owner: reference restored the bench handoff grammar that executable help owns"},
	{Group: AfterImplementSpec, File: ".bench/BENCH-reference.md", Kind: Forbid, Needle: "`bench worktree reset --to <commit> <target>` plans", Diagnostic: "fact owner: reference restored the bench worktree reset grammar that executable help owns"},
	{Group: AfterImplementSpec, File: ".bench/BENCH-reference.md", Kind: Forbid, Needle: "`bench retro <slug> (--body <markdown>", Diagnostic: "fact owner: reference restored the bench retro grammar that executable help owns"},
	{Group: AfterImplementSpec, File: ".bench/BENCH-reference.md", Kind: Require, Needle: "Before the first dispatch, the plan amendment makes the authored version 1 fence a version 2 plan.", Diagnostic: "fact owner: reference dropped the plan amendment from the authored version 1 fence to a version 2 plan"},
	{Group: AfterImplementSpec, File: ".bench/BENCH-reference.md", Kind: Forbid, Needle: "`.claude/skills/` carries only the", Diagnostic: "fact owner: reference restored the false claim that .claude/skills/ links only the craft skills"},
	{Group: AfterImplementSpec, File: ".bench/BENCH-reference.md", Kind: Forbid, Needle: "because Claude already has each phase as a command", Diagnostic: "fact owner: reference restored its copy of the Codex-only phase adapter rule that the Claude README owns"},
	{Group: AfterImplementSpec, File: ".bench/BENCH-reference.md", Kind: Forbid, Needle: skillLinkRule, Diagnostic: "fact owner: reference restored a copy of the Claude README's skill-link rule"},
	{Group: AfterImplementSpec, File: ".bench/BENCH-reference.md", Kind: Require, Needle: "`.claude/README.md` states which skills `.claude/skills/` links.", Diagnostic: "fact owner: reference dropped its pointer to the Claude README for the skill links"},
	{Group: AfterImplementSpec, File: ".claude/README.md", Kind: Require, Needle: skillLinkRule, Diagnostic: "fact owner: Claude README dropped the rule that .claude/skills/ links every skill with no same-named command"},
	{Group: AfterImplementSpec, File: ".claude/README.md", Kind: Forbid, Needle: "links only the `bench-craft-*` skills", Diagnostic: "fact owner: Claude README restored the false claim that .claude/skills/ links only the craft skills"},
	{Group: AfterImplementSpec, File: ".claude/README.md", Kind: Forbid, Needle: "`bench-writer` runs a user-directed write delegation", Diagnostic: "fact owner: Claude README restored bench-writer as the type of a user-directed write delegation only"},
}

// declaredLineAnchors pin how craft-line routes a ticket author. Require rows pin
// the binding of every ticket author to the spec's one declared line, the step 3
// escalation under the step 2 tier-move rule, and the step 5 top-tier pause
// outside `--delegate`. Forbid rows keep out the per-story ceiling, the per-ticket
// re-run of the decision table, the per-story collapse, the retired step 3 and
// step 5 wording, and craft-spec's per-story lines in its approval table.
var declaredLineAnchors = []Anchor{
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/SKILL.md", Kind: Require, Needle: "Every ticket author runs on the spec's declared `Line:`.", Diagnostic: "declared line: craft-line dropped the binding of every ticket author to the spec's declared line"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/SKILL.md", Kind: Forbid, Needle: "ceiling, not a binding", Diagnostic: "declared line: craft-line restored the per-story line as a ceiling, not a binding"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/SKILL.md", Kind: Forbid, Needle: "Re-run the decision table per ticket at charge time.", Diagnostic: "declared line: craft-line restored the per-ticket re-run of the decision table"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/SKILL.md", Kind: Forbid, Needle: "use the highest tier any story needs", Diagnostic: "declared line: craft-line restored the per-story collapse to the highest tier"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/SKILL.md", Kind: Forbid, Needle: "Report each collapsed line.", Diagnostic: "declared line: craft-line restored the report of each collapsed per-story line"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/SKILL.md", Kind: Require, Needle: "escalate immediately under the step 2 tier-move rule; no retry burned.", Diagnostic: "declared line: craft-line step 3 escalates without the step 2 tier-move rule"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/SKILL.md", Kind: Forbid, Needle: "escalate immediately; no retry burned.", Diagnostic: "declared line: craft-line restored the step 3 escalation without the step 2 tier-move rule"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/SKILL.md", Kind: Require, Needle: "Outside `--delegate`, a bump to the top tier pauses and asks the reviewer", Diagnostic: "declared line: craft-line step 5 dropped the `--delegate` exception from the top-tier pause"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/SKILL.md", Kind: Forbid, Needle: "Any bump to the top tier pauses and asks the reviewer", Diagnostic: "declared line: craft-line restored the top-tier pause for every run, `--delegate` included"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-spec/SKILL.md", Kind: Forbid, Needle: "stories and their lines", Diagnostic: "declared line: craft-spec restored per-story lines in the approval table"},
}

// retroCaptureAnchors pin how the final check writes and commits the retro. Require
// rows pin the scaffold-then-body route through `bench retro`, the pointer to the
// scaffold as the owner of the retro headings, the tracked-or-ignored commit rule,
// the Bench worktree that writes and lands a tracked retro, and the report's and the
// reference's pointers to that rule. Forbid rows keep out the report's copy of the
// retired no-commit rule, the drain-only exit, the reference's claim that the drain
// owns the retro's capture commit, the reference's copy of the commit rule, and a
// paste of the scaffold's heading list, which the retros package owns.
var retroCaptureAnchors = []Anchor{
	{Group: AfterImplementSpec, File: ".agents/commands/bench-final-check.md", Kind: Require, Needle: "Read `bench retro <slug> --scaffold`, then write the retro once with `bench retro <slug> --body <markdown>`.", Diagnostic: "retro capture: final check dropped the scaffold-then-body route through bench retro"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-final-check.md", Kind: Require, Needle: "The scaffold owns the retro headings and the calibration table header; keep them as the scaffold prints them.", Diagnostic: "retro capture: final check dropped its pointer to the scaffold as the owner of the retro headings"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-final-check.md", Kind: Require, Needle: "A tracked retro and its scorecard updates commit with the phase close.", Diagnostic: "retro capture: final check dropped the phase-close commit of a tracked retro and its scorecard updates"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-final-check.md", Kind: Require, Needle: "An ignored retro stays local until the next reviewer-approved capture drain.", Diagnostic: "retro capture: final check dropped the local route of an ignored retro"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-final-check.md", Kind: Require, Needle: "Capture the retro as \"Capture the implementation retro\" states.", Diagnostic: "retro capture: final check report dropped its pointer to the retro capture rule"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-final-check.md", Kind: Forbid, Needle: "Capture the retro without another", Diagnostic: "retro capture: final check report restored the no-commit retro rule"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-final-check.md", Kind: Forbid, Needle: "The retro leaves through the next reviewer-approved capture drain.", Diagnostic: "retro capture: final check restored the drain-only retro exit"},
	{Group: AfterImplementSpec, File: ".bench/BENCH-reference.md", Kind: Forbid, Needle: "owns their reviewed drain and its capture commit", Diagnostic: "retro capture: reference restored the drain as the owner of the retro capture commit"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-final-check.md", Kind: Require, Needle: "Write and commit them in a Bench worktree, and land that commit through `bench worktree land`.", Diagnostic: "retro capture: final check dropped the Bench worktree that writes, commits, and lands a tracked retro"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-final-check.md", Kind: Forbid, Needle: strings.Join(retros.RequiredHeadings(), "\n"), Diagnostic: "retro capture: final check restored a copy of the scaffold's retro heading list"},
	{Group: AfterImplementSpec, File: ".bench/BENCH-reference.md", Kind: Require, Needle: "`/bench-final-check` states when a tracked or an ignored retro commits.", Diagnostic: "retro capture: reference dropped its pointer to the final check's tracked-or-ignored retro rule"},
	{Group: AfterImplementSpec, File: ".bench/BENCH-reference.md", Kind: Forbid, Needle: "A tracked retro commits with the phase close", Diagnostic: "retro capture: reference restored its copy of the final check's tracked-or-ignored retro rule"},
}

// laneAndLandingAnchors pin one statement of the commit and landing split: a
// worktree `bench commit` runs the declared lane, and `bench worktree land` runs
// the whole-project gate. Forbid rows keep out the retired claims that the commit
// is the gate run or the source of the green verdict, the second gate before the
// landing, and the reference's claims that the landing boundary is
// unenforced and that a stale executable reruns the landing. The reference points
// to the operating guide's enforcement sentence, and a Forbid row reads that
// sentence's named constant so no copy returns there. Require rows pin the
// synthesis gate source, the final check's landing gate and worktree retirement,
// and the reviewer as the runner of the raw conflict merge.
var laneAndLandingAnchors = []Anchor{
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-synthesis/SKILL.md", Kind: Forbid, Needle: "`bench commit` gates the tree it lands", Diagnostic: "lane and landing: craft-synthesis restored the claim that bench commit gates the tree it lands"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-synthesis/SKILL.md", Kind: Require, Needle: "Take the green verdict from the whole-project gate. That gate is the landing's gate, or `bench worktree exec <target> -- bench gate` for a batch that waits for approval.", Diagnostic: "lane and landing: craft-synthesis dropped the whole-project gate as the source of the prose-only green verdict"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-synthesis/SKILL.md", Kind: Forbid, Needle: "Take that verdict from the commit itself.", Diagnostic: "lane and landing: craft-synthesis restored the commit as the source of the prose-only green verdict"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-synthesis/SKILL.md", Kind: Forbid, Needle: "A `bench gate` run before it grades the same tree twice and pays the oracle twice.", Diagnostic: "lane and landing: craft-synthesis restored the claim that a gate run before the commit pays the oracle twice"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-final-check.md", Kind: Forbid, Needle: "Run the external gate and commit work on green", Diagnostic: "lane and landing: final check description restored the claim that it runs the gate and commits on green"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-final-check.md", Kind: Forbid, Needle: "After a lane-only repair commit and before the landing, run the whole-tree gate on the source.", Diagnostic: "lane and landing: final check restored a second whole-project gate before the landing"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-final-check.md", Kind: Forbid, Needle: "Do not run `bench gate` first.", Diagnostic: "lane and landing: final check restored the ban on a gate run before the commit"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-final-check.md", Kind: Forbid, Needle: "the gate reuses a fresh green verdict for the identical tree and never re-pays it", Diagnostic: "lane and landing: final check restored the claim that the commit reuses a fresh green gate verdict"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-final-check.md", Kind: Forbid, Needle: "This command gates and commits them atomically.", Diagnostic: "lane and landing: final check restored the claim that bench commit gates and commits atomically"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-final-check.md", Kind: Forbid, Needle: "The commit already is the gate run", Diagnostic: "lane and landing: final check restored the claim that the commit is the gate run"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-final-check.md", Kind: Forbid, Needle: "the oracle run and landing are one command", Diagnostic: "lane and landing: final check restored the claim that the oracle run and the landing are one command"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-final-check.md", Kind: Forbid, Needle: "gate-then-commit path", Diagnostic: "lane and landing: final check restored the gate-then-commit path"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-final-check.md", Kind: Forbid, Needle: "then runs the gate and commits only on green", Diagnostic: "lane and landing: final check restored the claim that bench commit runs the gate and commits only on green"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-final-check.md", Kind: Require, Needle: "`bench worktree land` runs the whole-project gate on work that `bench commit` committed on a lane pass.", Diagnostic: "lane and landing: final check dropped the landing's whole-project gate on lane-pass commits"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-final-check.md", Kind: Require, Needle: "A merged spec awaiting retirement gets `bench spec retire <slug>` in a Bench worktree, and that worktree lands its `spec-retire: <slug>` commit through `bench worktree land`.", Diagnostic: "lane and landing: final check dropped the spec retirement in a Bench worktree and its landing"},
	{Group: AfterImplementSpec, File: ".bench/BENCH-reference.md", Kind: Forbid, Needle: "the rule is guidance, not a hook", Diagnostic: "lane and landing: reference restored the claim that the landing rule is guidance, not a hook"},
	{Group: AfterImplementSpec, File: ".bench/BENCH-reference.md", Kind: Forbid, Needle: WorktreeEnforcementMarker, Diagnostic: "lane and landing: reference restored a copy of the operating guide's worktree enforcement sentence"},
	{Group: AfterImplementSpec, File: ".bench/BENCH-reference.md", Kind: Require, Needle: "Every phase lands this way, and `.bench/BENCH.md` states how `bench commit` enforces that rule.", Diagnostic: "lane and landing: reference dropped its pointer to the operating guide's worktree enforcement sentence"},
	{Group: AfterImplementSpec, File: ".bench/BENCH-reference.md", Kind: Forbid, Needle: "A stale Bench executable is rebuilt, and the landing re-runs under it.", Diagnostic: "lane and landing: reference restored the claim that the landing rebuilds a stale Bench executable and re-runs"},
	{Group: AfterImplementSpec, File: ".bench/BENCH-reference.md", Kind: Require, Needle: "the reviewer merges the destination into the source worktree with raw Git", Diagnostic: "lane and landing: reference dropped the reviewer as the runner of the raw Git conflict merge"},
}

// defaultWorkflowAnchors keep plan expansion within the approved behavior while
// allowing the orchestrator to update the plan before new evidence is used.
var defaultWorkflowAnchors = []Anchor{
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-spec/SKILL.md", Kind: RequireInSection, Section: "Slicing a build for delegates", Needle: "During a build, `.bench/BENCH.md` owns approved in-scope plan expansion.", Diagnostic: "retained workflow: craft-spec dropped the canonical plan-expansion owner"},
	{Group: AfterImplementSpec, File: ".bench/BENCH.md", Kind: Require, Needle: "When chunk boundaries change, record old-to-new stable IDs.", Diagnostic: "retained workflow: operating guide dropped changed-chunk identity mapping"},
	{Group: AfterImplementSpec, File: ".bench/BENCH.md", Kind: Require, Needle: "Before using a plan expansion, update the affected spec and tickets; preserve acceptance coverage, dependencies, review checkpoints, existing checks, pass criteria, and required behavior.", Diagnostic: "retained workflow: operating guide dropped plan-update timing or preserved guarantees"},
	{Group: AfterImplementSpec, File: ".bench/BENCH.md", Kind: Require, Needle: "Record every plan or gate expansion with `bench learning`, including what changed, why, and verification; `/bench-drain` owns its later disposition.", Diagnostic: "retained workflow: operating guide dropped expansion learning and drain ownership"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-implement-spec.md", Kind: Require, Needle: "When evidence requires an in-scope plan, `Writes:`, or gate expansion, apply `.bench/BENCH.md`'s approved plan-expansion policy before using it.", Diagnostic: "retained workflow: implementation phase dropped plan-expansion timing"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-gate/SKILL.md", Kind: Require, Needle: "An in-scope gate addition during implementation follows `.bench/BENCH.md`'s approved plan-expansion policy before the author uses it.", Diagnostic: "retained workflow: craft-gate dropped approved expansion timing"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-tickets/SKILL.md", Kind: Require, Needle: "`Writes:` predicts the touched paths; `.bench/BENCH.md` owns how the orchestrator updates that expectation before an approved in-scope expansion is used.", Diagnostic: "retained workflow: craft-tickets restored Writes as an approval boundary"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-delegate/references/delegation-discipline.md", Kind: Forbid, Needle: "A user-directed write delegate treats `Writes:` as an expectation.", Diagnostic: "retained workflow: delegation discipline scoped the Writes expectation to a user-directed write delegate"},
}

// delegatedWorkflowAnchors pin the opt-in delegated exception and every rule of
// who authors, repairs, probes, commits, and lands a ticket: the fresh author
// and repair sessions, the bench-writer role, the lane-pass commit and landing
// bans, the stash and bench probe duties, and the retired copies that a
// Forbid row keeps out (copy-aside probes, the main-checkout build, the
// resume-clean step, and phase-command copies of owner rules). They join the
// retained-workflow family because the same owners carry these contracts, and
// a reader who loses one clause loses the boundary between them. Each needle
// is the instruction's one source. A Forbid row that keeps a copy of an owner
// sentence out reads the named constant of that sentence's Require row. No anchor
// claims to prove native dispatch.
var delegatedWorkflowAnchors = []Anchor{
	{Group: AfterImplementSpec, File: ".bench/BENCH.md", Kind: Require, Needle: "`--delegate` applies only to an approved `$bench-implement-spec --full <spec>` run with an approved ticket graph.", Diagnostic: "retained workflow: operating guide dropped the delegated opt-in entry"},
	{Group: AfterImplementSpec, File: ".bench/BENCH.md", Kind: Require, Needle: "A ticket in a dependent chunk waits for every prerequisite chunk checkpoint.", Diagnostic: "retained workflow: operating guide dropped the delegated prerequisite-checkpoint wait"},
	{Group: AfterImplementSpec, File: ".bench/BENCH.md", Kind: Require, Needle: "A same-chunk successor ticket starts after its predecessor ticket commits green.", Diagnostic: "retained workflow: operating guide dropped the green predecessor dispatch rule"},
	{Group: AfterImplementSpec, File: ".bench/BENCH.md", Kind: Require, Needle: "A pending or red predecessor commit stops that successor dispatch.", Diagnostic: "retained workflow: operating guide dropped the pending-or-red predecessor stop"},
	{Group: AfterImplementSpec, File: ".bench/BENCH.md", Kind: Require, Needle: "`--delegate` adds concurrent authors and the full tier range.", Diagnostic: "fresh ticket author: operating guide dropped the concurrent authors and the full tier range of `--delegate`"},
	{Group: AfterImplementSpec, File: ".bench/BENCH.md", Kind: Require, Needle: "A post-review repair goes to a fresh repair session for each affected ticket, and that session reruns the ticket's verification with current repair coverage. The plan records each repair session as a new assignment with the trigger `user-directed`. At final reconciliation, the orchestrator does not repair. A finding there goes to a fresh repair session for the ticket whose `Writes:` line holds the path. A finding on a path that no `Writes:` line holds is a material acceptance shortfall.", Diagnostic: "fresh ticket author: operating guide dropped the fresh repair session for each affected ticket"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-delegate/SKILL.md", Kind: Forbid, Needle: "A spec-backed ticket goes to a fresh author session on its integration source", Diagnostic: "fresh ticket author: craft-delegate restored its copy of the fresh author session rule that the operating guide owns"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-delegate/SKILL.md", Kind: Forbid, Needle: "Repairs return to the retained implementation session.", Diagnostic: "fresh ticket author: craft-delegate restored the repair return to the retained session"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-delegate/SKILL.md", Kind: Require, Needle: "`craft-line` owns a change of implementation model or session.", Diagnostic: "fresh ticket author: craft-delegate dropped craft-line as the owner of a change of implementation model or session"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-delegate/SKILL.md", Kind: Require, Needle: "Every write delegate runs as `bench-writer`: a fresh ticket author, a repair session, and a user-directed write delegation.", Diagnostic: "fresh ticket author: craft-delegate dropped bench-writer as the type of a fresh ticket author and a repair session"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-delegate/SKILL.md", Kind: Forbid, Needle: "delegation runs as `bench-writer`", Diagnostic: "fresh ticket author: craft-delegate restored bench-writer as the type of a user-directed write delegation only"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-delegate/SKILL.md", Kind: Forbid, Needle: "A user-directed write-delegation from a spec carries", Diagnostic: "fresh ticket author: craft-delegate scoped the coverage-row charge to a user-directed write-delegation"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-delegate/SKILL.md", Kind: Require, Needle: "A ticket author commits its ticket on a lane pass before the next charge starts.", Diagnostic: "fresh ticket author: craft-delegate dropped the ticket author commit on a lane pass"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-delegate/SKILL.md", Kind: Forbid, Needle: "the coordinator runs `bench commit` per worktree", Diagnostic: "fresh ticket author: craft-delegate restored the coordinator commit per worktree"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-delegate/SKILL.md", Kind: Forbid, Needle: "stops at diff-ready", Diagnostic: "fresh ticket author: craft-delegate restored the diff-ready stop for every write delegate"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-delegate/SKILL.md", Kind: Forbid, Needle: "Stop at diff ready;", Diagnostic: "fresh ticket author: craft-delegate charge example restored the uncommitted diff-ready stop"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-delegate/SKILL.md", Kind: Forbid, Needle: "Share a worktree only when a delegate's work depends on another's output.", Diagnostic: "fresh ticket author: craft-delegate restored the dependency-only worktree share rule"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-delegate/SKILL.md", Kind: Require, Needle: "The coordinator probes a user-directed write delegate's returned tree independently before landing it.", Diagnostic: "fresh ticket author: craft-delegate dropped the user-directed scope of the returned-tree coordinator probe"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-delegate/SKILL.md", Kind: Forbid, Needle: "A ticket delegate returns focused evidence", Diagnostic: "fresh ticket author: craft-delegate restored the returned-tree coordinator probe for every ticket delegate"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-delegate/SKILL.md", Kind: Forbid, Needle: "the destructive-git guard refuses it", Diagnostic: "fresh ticket author: craft-delegate restored the false claim that the guard refuses every git stash"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-delegate/SKILL.md", Kind: Require, Needle: "the destructive-git guard refuses only `git stash drop` and `git stash clear`.", Diagnostic: "fresh ticket author: craft-delegate dropped the guard's real git stash deny surface"},
	{Group: AfterImplementSpec, File: ".claude/agents/bench-writer.md", Kind: Require, Needle: "description: The Bench write delegate for a fresh ticket author, a repair session, or a user-directed write delegation.", Diagnostic: "fresh ticket author: bench-writer description dropped the fresh ticket author or the repair session"},
	{Group: AfterImplementSpec, File: ".claude/agents/bench-writer.md", Kind: Require, Needle: "A ticket author or a repair author commits its ticket on a lane pass and does not run `bench worktree land`.", Diagnostic: "fresh ticket author: bench-writer dropped the lane-pass commit of a ticket or repair author, or its landing ban"},
	{Group: AfterImplementSpec, File: ".claude/agents/bench-writer.md", Kind: Require, Needle: "focused checks green, and it does not land the diff.", Diagnostic: "fresh ticket author: bench-writer dropped the landing ban of a user-directed delegate"},
	{Group: AfterImplementSpec, File: ".claude/agents/bench-writer.md", Kind: Forbid, Needle: "The user directed this delegation", Diagnostic: "fresh ticket author: bench-writer restored the user-directed premise for every write delegate"},
	{Group: AfterImplementSpec, File: ".claude/agents/bench-writer.md", Kind: Forbid, Needle: "Stop at a diff that is ready, with the focused checks green.", Diagnostic: "fresh ticket author: bench-writer restored the uncommitted-diff stop for every write delegate"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/SKILL.md", Kind: RequireInSection, Section: "Retained implementation continuation", Needle: "The continuation rules below govern the pre-review work of each ticket author", Diagnostic: "fresh ticket author: craft-line dropped the continuation rules for each ticket author"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/SKILL.md", Kind: Require, Needle: "Outside `--delegate`, a tier move of a fresh ticket author asks the reviewer first.", Diagnostic: "fresh ticket author: craft-line dropped the reviewer stop before a tier move of a fresh author"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-tickets/SKILL.md", Kind: Require, Needle: "Spec-backed builds work the unblocked frontier with one fresh author for each ticket.", Diagnostic: "fresh ticket author: craft-tickets dropped the frontier with one fresh author for each ticket"},
	{Group: AfterImplementSpec, File: "README.md", Kind: Require, Needle: "Each ticket gets a fresh author session.", Diagnostic: "fresh ticket author: README dropped the fresh author session for each ticket"},
	{Group: AfterImplementSpec, File: ".bench/BENCH.md", Kind: Forbid, Needle: "Production repairs stay with the recorded ticket author.", Diagnostic: "fresh ticket author: operating guide restored the ticket-author repair ownership"},
	{Group: AfterImplementSpec, File: ".bench/BENCH-reference.md", Kind: Require, Needle: "the plan amendment declares version 2 with a delegate execution block. The amendment splits each chunk verification into one verification for each ticket.", Diagnostic: "fresh ticket author: reference dropped the version 2 plan amendment or its verification for each ticket"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/SKILL.md", Kind: Require, Needle: "`--delegate` authorizes selection and eligible escalation through every configured tier, including top.", Diagnostic: "retained workflow: craft-line dropped the delegated tier authorization"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/SKILL.md", Kind: Require, Needle: "An unavailable or unbound model stops that dispatch without a substitution.", Diagnostic: "retained workflow: craft-line dropped the unbound delegated model stop"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/SKILL.md", Kind: Require, Needle: "The declared author limit counts concurrently active ticket writers, not retained idle author sessions.", Diagnostic: "retained workflow: craft-line dropped the active-writer author limit"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/SKILL.md", Kind: Require, Needle: "Every delegated review axis uses the invoking harness's configured mid binding at high effort.", Diagnostic: "retained workflow: craft-line dropped the delegated mid review route"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-delegate/references/delegation-discipline.md", Kind: RequireInSection, Section: "Delegated author transfer", Needle: "Two completed attempts with no progress permit a replacement or a model change only after a recorded reassessment.", Diagnostic: "retained workflow: delegation discipline dropped the no-progress transfer trigger"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-delegate/references/delegation-discipline.md", Kind: RequireInSection, Section: "Delegated author transfer", Needle: "A recorded terminal author failure permits a replacement or a model change.", Diagnostic: "retained workflow: delegation discipline dropped the terminal-failure transfer trigger"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-delegate/references/delegation-discipline.md", Kind: RequireInSection, Section: "Delegated author transfer", Needle: "An exhausted declared author cap permits a replacement or a model change.", Diagnostic: "retained workflow: delegation discipline dropped the cap-exhaustion transfer trigger"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-delegate/references/delegation-discipline.md", Kind: RequireInSection, Section: "Delegated author transfer", Needle: "A lost author session permits a replacement or a model change.", Diagnostic: "retained workflow: delegation discipline dropped the lost-session transfer trigger"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-delegate/references/delegation-discipline.md", Kind: RequireInSection, Section: "Delegated author transfer", Needle: "A post-review repair under the standing policy of `.bench/BENCH.md` permits a `user-directed` replacement of the author by a fresh repair session.", Diagnostic: "fresh ticket author: delegation discipline dropped the user-directed transfer for a post-review repair"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-delegate/references/delegation-discipline.md", Kind: RequireInSection, Section: "Delegated author transfer", Needle: "Every author transfer waits for confirmed termination of the old writer.", Diagnostic: "retained workflow: delegation discipline dropped the confirmed writer termination"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-delegate/references/delegation-discipline.md", Kind: RequireInSection, Section: "Delegated author transfer", Needle: "Outside `--delegate`, a model change under any trigger is a tier move, and it asks the reviewer first.", Diagnostic: "fresh ticket author: delegation discipline let a transfer trigger move the tier outside --delegate without the reviewer"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-delegate/references/delegation-discipline.md", Kind: RequireInSection, Section: "In the charge", Needle: "Every write delegate treats `Writes:` as an expectation.", Diagnostic: "fresh ticket author: delegation discipline dropped the Writes expectation for every write delegate"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-delegate/references/delegation-discipline.md", Kind: Forbid, Needle: "Probe a tracked file that has pending changes with a copy aside.", Diagnostic: "fresh ticket author: delegation discipline restored the copy-aside probe that bench probe replaces"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-delegate/references/delegation-discipline.md", Kind: Forbid, Needle: "mutated bytes against the copy aside", Diagnostic: "fresh ticket author: delegation discipline restored the copy-aside confirmation of the mutated bytes"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-delegate/references/delegation-discipline.md", Kind: Forbid, Needle: "may run in the main checkout", Diagnostic: "fresh ticket author: delegation discipline restored the main-checkout build exception"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-delegate/references/delegation-discipline.md", Kind: Forbid, Needle: "`bench resume-clean`", Diagnostic: "fresh ticket author: delegation discipline restored the internal resume-clean verb as a recovery step"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-delegate/references/delegation-discipline.md", Kind: Forbid, Needle: "on the integration source after every ticket commit and before the next charge", Diagnostic: "fresh ticket author: delegation discipline restored its copy of the build preflight rule that the build phase owns"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-delegate/references/delegation-discipline.md", Kind: Forbid, Needle: "a slow tool call is not a failed attempt", Diagnostic: "fresh ticket author: delegation discipline restored its copy of the attempt definition that craft-line owns"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-delegate/references/delegation-discipline.md", Kind: RequireInSection, Section: "Read-only returns", Needle: "A shared-worktree reader probes only through `bench probe` and reads its `restored` cell.", Diagnostic: "fresh ticket author: delegation discipline dropped the bench probe restore duty of a shared-worktree reader"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-implement-spec.md", Kind: Require, Needle: "It refuses without `--full`, an approved spec, or an approved ticket graph.", Diagnostic: "retained workflow: implementation phase dropped the delegated entry refusals"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-implement-spec.md", Kind: Require, Needle: "Declare the configured model, effort, iteration cap, and author limit before the first dispatch.", Diagnostic: "retained workflow: implementation phase dropped the delegated dispatch declaration"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-implement-spec.md", Kind: Require, Needle: "A resumed delegated run keeps the recorded identities, source pins, replacement history, and pending obligations.", Diagnostic: "retained workflow: implementation phase dropped delegated resumption contents"},
	{Group: AfterImplementSpec, File: ".bench/BENCH.md", Kind: Require, Needle: chunkTipReviewFence, Diagnostic: "retained workflow: operating guide dropped the integrated chunk-tip review fence"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-review-implementation.md", Kind: Forbid, Needle: "A delegated chunk review starts after every ticket of the chunk reaches the integrated chunk tip.", Diagnostic: "fresh ticket author: review phase restored its copy of the chunk-review start rule that the operating guide owns"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-review-implementation.md", Kind: Forbid, Needle: "Repeat delegated review only for a later semantic delta", Diagnostic: "fresh ticket author: review phase restored its copy of the review-repeat rule that the operating guide owns"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-review-implementation.md", Kind: Forbid, Needle: "After the last chunk, the orchestrator reconciles overall acceptance and integration before landing.", Diagnostic: "fresh ticket author: review phase restored its copy of the final reconciliation rule that the operating guide owns"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-implement-spec.md", Kind: Forbid, Needle: "Repeat delegated review only when a later delta or cross-chunk concern invalidates prior evidence.", Diagnostic: "fresh ticket author: implementation phase restored its copy of the review-repeat rule that the operating guide owns"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-review-implementation.md", Kind: Forbid, Needle: reviewRepeatRule, Diagnostic: "fresh ticket author: review phase restored a copy of the operating guide's review-repeat rule"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-review-implementation.md", Kind: Forbid, Needle: finalReconciliationRule, Diagnostic: "fresh ticket author: review phase restored a copy of the operating guide's final reconciliation rule"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-review-implementation.md", Kind: Forbid, Needle: chunkTipReviewFence, Diagnostic: "fresh ticket author: review phase restored a copy of the operating guide's chunk-tip review fence"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-implement-spec.md", Kind: Forbid, Needle: reviewRepeatRule, Diagnostic: "fresh ticket author: implementation phase restored a copy of the operating guide's review-repeat rule"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-review-implementation.md", Kind: RequireInSection, Section: "Review modes", Needle: "`.bench/BENCH.md` owns when a chunk review starts, when a delegated review repeats, and the final reconciliation after the last chunk.", Diagnostic: "fresh ticket author: review phase dropped its pointer to the operating guide's chunk-review cadence"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-final-check.md", Kind: Require, Needle: "For other work, if I approve, fix it and re-run the gate.", Diagnostic: "fresh ticket author: final check dropped the other-work scope of the approve-then-fix route"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-implement-spec.md", Kind: Forbid, Needle: "For a ticket author, raise the effort and resume; a tier move asks the reviewer first.", Diagnostic: "fresh ticket author: implementation phase restored its copy of the tier ladder without the `--delegate` exception that craft-line owns"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-debug.md", Kind: Forbid, Needle: "The coordinator validates the report and reslices", Diagnostic: "fresh ticket author: debug phase restored the coordinator reslice of an out-of-fence cause"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-debug.md", Kind: Require, Needle: "An out-of-fence cause follows `.bench/BENCH.md`'s plan-expansion policy, or the reviewer's split for a scope change.", Diagnostic: "fresh ticket author: debug phase dropped the plan-expansion or reviewer-split route of an out-of-fence cause"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-final-check.md", Kind: Forbid, Needle: "the author's final acceptance and integration command results", Diagnostic: "fresh ticket author: final check restored the author as the performer of the final acceptance and integration results"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-final-check.md", Kind: Require, Needle: "The review record retains the orchestrator's final `integration-verification` results.", Diagnostic: "fresh ticket author: final check dropped the orchestrator's final integration-verification results"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-final-check.md", Kind: Require, Needle: "A spec-backed red goes to a fresh repair session under `.bench/BENCH.md`'s repair rule.", Diagnostic: "fresh ticket author: final check dropped the fresh repair session for a spec-backed red"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-review-implementation.md", Kind: Require, Needle: "Each delegated axis excludes the orchestrator and every current and former author of the run.", Diagnostic: "retained workflow: review phase dropped the delegated axis exclusions"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-final-check.md", Kind: Require, Needle: "A delegated exit reconciles every known invocation against the recorded assessment attempts.", Diagnostic: "retained workflow: final check dropped the delegated account reconciliation"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-final-check.md", Kind: Require, Needle: "That account carries failed dispatches, every author, every review axis, diagnostics, verification, and orchestration work.", Diagnostic: "retained workflow: final check dropped an account inventory member"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-final-check.md", Kind: Require, Needle: "Delegated verification launches no paid comparison and changes no model default.", Diagnostic: "retained workflow: final check dropped the no-paid-comparison boundary"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-final-check.md", Kind: Require, Needle: "The orchestrator performs the final verification on the final source before the landing.", Diagnostic: "retained workflow: final check dropped the orchestrator final verification"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-tickets/SKILL.md", Kind: Require, Needle: "A delegated run keeps these serial green ticket checkpoints under the operating guide's delegated policy.", Diagnostic: "retained workflow: craft-tickets dropped the delegated serial ticket checkpoint"},
}

// chunkTipReviewFence is the `.bench/BENCH.md` owner sentence for the chunk-review
// start. Its Require row and the Forbid row that keeps a review-phase copy out read
// this one constant.
const chunkTipReviewFence = "Every ticket contribution reaches the integrated chunk tip before that chunk's review begins."

var implementationContinuationAnchors = []Anchor{
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/SKILL.md", Kind: RequireInSection, Section: "The declaration", Needle: "The iteration policy is a numeric cap or an explicit `uncapped` policy.", Diagnostic: "implementation continuation: craft-line dropped the explicit uncapped policy"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/SKILL.md", Kind: RequireInSection, Section: "Retained implementation continuation", Needle: "A verified acceptance improvement is progress.", Diagnostic: "implementation continuation: craft-line dropped verified acceptance progress"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/SKILL.md", Kind: RequireInSection, Section: "Retained implementation continuation", Needle: "An expected TDD red is not an attempt.", Diagnostic: "implementation continuation: craft-line counted expected TDD reds as attempts"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/SKILL.md", Kind: RequireInSection, Section: "Retained implementation continuation", Needle: "After two completed attempts with no progress, reassess before the next implementation attempt.", Diagnostic: "implementation continuation: craft-line dropped the two-attempt reassessment threshold"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/SKILL.md", Kind: RequireInSection, Section: "Retained implementation continuation", Needle: "Stop when the run reaches an explicit user budget.", Diagnostic: "implementation continuation: craft-line dropped the explicit user-budget stop"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/SKILL.md", Kind: RequireInSection, Section: "Retained implementation continuation", Needle: "If no useful next check remains, report the unresolved blocker and the smallest decision or evidence needed.", Diagnostic: "implementation continuation: craft-line dropped the actionable blocked handoff"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/SKILL.md", Kind: RequireInSection, Section: "Retained implementation continuation", Needle: "New useful evidence is progress when it changes the next action.", Diagnostic: "implementation continuation: craft-line dropped useful-evidence progress"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/SKILL.md", Kind: RequireInSection, Section: "Retained implementation continuation", Needle: "Continue while progress holds inside the approved scope.", Diagnostic: "implementation continuation: craft-line dropped continuation while progress holds"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/SKILL.md", Kind: RequireInSection, Section: "Retained implementation continuation", Needle: "An individual tool call is not an attempt.", Diagnostic: "implementation continuation: craft-line counted individual tool calls as attempts"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/SKILL.md", Kind: RequireInSection, Section: "Retained implementation continuation", Needle: "State the changed hypothesis and the next discriminating check.", Diagnostic: "implementation continuation: craft-line dropped the discriminating reassessment check"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/SKILL.md", Kind: RequireInSection, Section: "Retained implementation continuation", Needle: "Stop when the run exhausts a selected numeric cap.", Diagnostic: "implementation continuation: craft-line dropped numeric-cap exhaustion"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/SKILL.md", Kind: RequireInSection, Section: "Retained implementation continuation", Needle: "Stop dependent implementation for a required user decision.", Diagnostic: "implementation continuation: craft-line dropped the required-decision stop"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/SKILL.md", Kind: RequireInSection, Section: "Retained implementation continuation", Needle: "Stop for an external blocker when no independent work remains.", Diagnostic: "implementation continuation: craft-line dropped the terminal external-blocker stop"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/SKILL.md", Kind: RequireInSection, Section: "Retained implementation continuation", Needle: "Stop immediately when the user cancels.", Diagnostic: "implementation continuation: craft-line dropped the cancellation stop"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/SKILL.md", Kind: RequireInSection, Section: "Retained implementation continuation", Needle: "A diagnostic-only action is not a completed implementation-and-verification attempt.", Diagnostic: "implementation continuation: craft-line counted diagnostic-only work as an attempt"},
	{Group: AfterImplementSpec, File: ".bench/BENCH.md", Kind: RequireInSection, Section: "Workflow", Needle: "`craft-line` owns the retained implementation continuation policy.", Diagnostic: "implementation continuation: operating guide dropped the continuation-policy pointer"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-implement-spec.md", Kind: RequireInSection, Section: "Build", Needle: "Apply `craft-line`'s retained implementation continuation policy throughout the ticket graph.", Diagnostic: "implementation continuation: implementation phase dropped the continuation-policy action"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/SKILL.md", Kind: RequireInSection, Section: "Retained implementation continuation", Needle: "An uncapped implementation has no artificial iteration stop within the approved spec.", Diagnostic: "implementation continuation: craft-line restored an artificial stop for uncapped work"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/SKILL.md", Kind: RequireInSection, Section: "Retained implementation continuation", Needle: "After reassessment, the ticket author can invoke `$bench-debug`.", Diagnostic: "implementation continuation: craft-line dropped the debug route"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-delegate/SKILL.md", Kind: Forbid, Needle: "A diagnostic helper can inspect evidence, but it receives no implementation or repair assignment.", Diagnostic: "implementation continuation: craft-delegate restored its copy of the diagnostic helper boundary that the operating guide owns"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/SKILL.md", Kind: RequireInSection, Section: "Retained implementation continuation", Needle: "A diagnostic route does not change the ticket author's session.", Diagnostic: "implementation continuation: diagnostic escalation changed the author session"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/SKILL.md", Kind: RequireInSection, Section: "Ticketed-build stage defaults", Needle: "The ticket author can adjust effort in its own session and reports the change.", Diagnostic: "implementation continuation: craft-line dropped the author's effort adjustment"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-delegate/SKILL.md", Kind: RequireInSection, Section: "Delegate or retain", Needle: "During implementation, brief higher-tier diagnostic consultation is pre-approved through the top tier.", Diagnostic: "implementation continuation: craft-delegate dropped top-tier diagnostic pre-approval"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-delegate/references/delegation-discipline.md", Kind: RequireInSection, Section: "Read-only returns", Needle: "A diagnostic request contains only one question, the relevant error, minimal code, and attempted hypotheses.", Diagnostic: "implementation continuation: delegation discipline expanded diagnostic request context"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-delegate/references/delegation-discipline.md", Kind: RequireInSection, Section: "Read-only returns", Needle: "A diagnostic return contains a short diagnosis and the next check.", Diagnostic: "implementation continuation: delegation discipline dropped the short diagnostic return"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/SKILL.md", Kind: RequireInSection, Section: "Retained implementation continuation", Needle: "A diagnostic route does not change the ticket author's model.", Diagnostic: "implementation continuation: diagnostic escalation changed the author model"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-delegate/references/delegation-discipline.md", Kind: RequireInSection, Section: "Read-only returns", Needle: "Record the actual consultation line used.", Diagnostic: "implementation continuation: delegation discipline dropped the actual consultation line"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-delegate/references/delegation-discipline.md", Kind: RequireInSection, Section: "Read-only returns", Needle: "If the selected model is unavailable, report the failure and use an available authorized diagnostic route without an undeclared model substitution.", Diagnostic: "implementation continuation: delegation discipline allowed an undeclared model substitution"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/references/bounded-repair-policy.md", Kind: RequireInSection, Section: "Scope and allowance", Needle: "Each implementation chunk permits at most two repair cycles after its initial review.", Diagnostic: "implementation continuation: bounded repair dropped fixed allowance"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/references/bounded-repair-policy.md", Kind: Forbid, Needle: "This allowance applies to retained, full, delegated, unattended, and light-path implementation runs.", Diagnostic: "implementation continuation: bounded repair restored the retired mode list"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/references/bounded-repair-policy.md", Kind: RequireInSection, Section: "Scope and allowance", Needle: "This allowance applies to every implementation run, the light path included.", Diagnostic: "implementation continuation: bounded repair dropped its scope over every implementation run"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/references/bounded-repair-policy.md", Kind: RequireInSection, Section: "Scope and allowance", Needle: "Light-path work counts as one chunk when it receives review findings.", Diagnostic: "implementation continuation: bounded repair dropped light-path chunk"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/references/bounded-repair-policy.md", Kind: RequireInSection, Section: "Scope and allowance", Needle: "Initial implementation, pre-review checks, and the first review consume no repair cycles.", Diagnostic: "implementation continuation: bounded repair dropped initial-work exclusion"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/references/bounded-repair-policy.md", Kind: RequireInSection, Section: "Scope and allowance", Needle: "A repair cycle is one repair attempt and verification of its affected findings. It can address several findings.", Diagnostic: "implementation continuation: bounded repair dropped cycle unit"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/references/bounded-repair-policy.md", Kind: RequireInSection, Section: "Scope and allowance", Needle: "Individual tool calls and unchanged verification reruns consume no additional repair cycles.", Diagnostic: "implementation continuation: bounded repair dropped verification-only exclusion"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/references/bounded-repair-policy.md", Kind: RequireInSection, Section: "Scope and allowance", Needle: "The allowance takes precedence over continuation while progress holds after initial review.", Diagnostic: "implementation continuation: bounded repair dropped progress precedence"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/references/bounded-repair-policy.md", Kind: RequireInSection, Section: "Scope and allowance", Needle: "Progress does not extend the allowance. A fresh review does not reset the same chunk's count.", Diagnostic: "implementation continuation: bounded repair dropped progress and review continuity"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/references/bounded-repair-policy.md", Kind: RequireInSection, Section: "Scope and allowance", Needle: "An uncapped implementation line does not remove this allowance.", Diagnostic: "implementation continuation: bounded repair dropped uncapped-line boundary"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/references/bounded-repair-policy.md", Kind: RequireInSection, Section: "Scope and allowance", Needle: "Only an explicit reviewer decision extends the allowance; record the additional work it permits.", Diagnostic: "implementation continuation: bounded repair dropped reviewer extension"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/references/bounded-repair-policy.md", Kind: RequireInSection, Section: "Classification and completion", Needle: "Before accepting a blocker, cite its binding requirement or concrete defect evidence.", Diagnostic: "implementation continuation: bounded repair dropped blocker evidence"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/references/bounded-repair-policy.md", Kind: RequireInSection, Section: "Classification and completion", Needle: "The following unresolved conditions remain blocking, including at exhaustion:", Diagnostic: "implementation continuation: bounded repair dropped exhaustion classification"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/references/bounded-repair-policy.md", Kind: RequireInSection, Section: "Classification and completion", Needle: "A required check fails.", Diagnostic: "implementation continuation: bounded repair dropped required checks"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/references/bounded-repair-policy.md", Kind: RequireInSection, Section: "Classification and completion", Needle: "An approved acceptance requirement fails.", Diagnostic: "implementation continuation: bounded repair dropped acceptance failures"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/references/bounded-repair-policy.md", Kind: RequireInSection, Section: "Classification and completion", Needle: "A concrete correctness defect remains, even with a green gate.", Diagnostic: "implementation continuation: bounded repair dropped correctness defects"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/references/bounded-repair-policy.md", Kind: RequireInSection, Section: "Classification and completion", Needle: "A concrete safety defect remains, even with a green gate.", Diagnostic: "implementation continuation: bounded repair dropped safety defects"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/references/bounded-repair-policy.md", Kind: RequireInSection, Section: "Classification and completion", Needle: "A documented mandatory standard fails, even without an automated check.", Diagnostic: "implementation continuation: bounded repair dropped mandatory standards"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/references/bounded-repair-policy.md", Kind: RequireInSection, Section: "Classification and completion", Needle: "A preference without a binding requirement or concrete defect remains optional advice.", Diagnostic: "implementation continuation: bounded repair dropped optional classification"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/references/bounded-repair-policy.md", Kind: RequireInSection, Section: "Classification and completion", Needle: "Give optional advice no disposition or finding ID, and exclude it from finding totals.", Diagnostic: "implementation continuation: bounded repair dropped optional census"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/references/bounded-repair-policy.md", Kind: RequireInSection, Section: "Classification and completion", Needle: "Retain optional advice in a separate advice section of the native excerpt and the review pickup.", Diagnostic: "implementation continuation: bounded repair dropped optional retention"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/references/bounded-repair-policy.md", Kind: RequireInSection, Section: "Classification and completion", Needle: "A native review can pass with no finding IDs while its prose retains optional advice.", Diagnostic: "implementation continuation: bounded repair dropped optional pass"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/references/bounded-repair-policy.md", Kind: RequireInSection, Section: "Classification and completion", Needle: "After substantive repairs, obtain current results or permitted native reaffirmations from every review axis.", Diagnostic: "implementation continuation: bounded repair dropped current review evidence"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/references/bounded-repair-policy.md", Kind: RequireInSection, Section: "Classification and completion", Needle: "A review-record prose correction is evidence-only only when it changes no finding, source identity, observation, disposition, or verification claim.", Diagnostic: "implementation continuation: bounded repair dropped evidence-only definition"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/references/bounded-repair-policy.md", Kind: RequireInSection, Section: "Classification and completion", Needle: "Evidence-only corrections consume no repair cycle. Batch all cited corrections before verification.", Diagnostic: "implementation continuation: bounded repair counted evidence-only prose"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/references/bounded-repair-policy.md", Kind: RequireInSection, Section: "Classification and completion", Needle: "Only the issuing axis reaffirms an evidence-only correction unless it invalidates another axis's evidence.", Diagnostic: "implementation continuation: bounded repair widened prose reaffirmation"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/references/bounded-repair-policy.md", Kind: RequireInSection, Section: "Classification and completion", Needle: "The coordinator commits the final review record before starting the whole-project gate. It does not edit the gate subject while the gate runs.", Diagnostic: "implementation continuation: bounded repair started gate before evidence freeze"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/references/bounded-repair-policy.md", Kind: RequireInSection, Section: "Classification and completion", Needle: "Unresolved findings, stale source identity, missing axes, and incomplete verification still block completion.", Diagnostic: "implementation continuation: bounded repair dropped completion safeguards"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/references/bounded-repair-policy.md", Kind: RequireInSection, Section: "State and handoff", Needle: "Retain the consumed count and any explicit reviewer extension in the existing review pickup.", Diagnostic: "implementation continuation: bounded repair dropped pickup state"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/references/bounded-repair-policy.md", Kind: RequireInSection, Section: "State and handoff", Needle: "For light-path work without a pickup, retain that state in the existing session handoff.", Diagnostic: "implementation continuation: bounded repair dropped light-path state"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/references/bounded-repair-policy.md", Kind: RequireInSection, Section: "State and handoff", Needle: "Before a resumed session starts another repair cycle, read the retained state.", Diagnostic: "implementation continuation: bounded repair dropped resume state"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/references/bounded-repair-policy.md", Kind: RequireInSection, Section: "State and handoff", Needle: "If the count is missing, reconstruct it from available evidence; never assume zero.", Diagnostic: "implementation continuation: bounded repair dropped missing-count reconstruction"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/references/bounded-repair-policy.md", Kind: RequireInSection, Section: "State and handoff", Needle: "If evidence cannot establish the remaining allowance, return that uncertainty to the reviewer before another repair cycle.", Diagnostic: "implementation continuation: bounded repair dropped unknown-count stop"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/references/bounded-repair-policy.md", Kind: RequireInSection, Section: "State and handoff", Needle: "At exhaustion with blockers, report the consumed allowance, completed repairs, remaining blockers, and the needed reviewer decision.", Diagnostic: "implementation continuation: bounded repair dropped exhaustion report"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/references/bounded-repair-policy.md", Kind: RequireInSection, Section: "State and handoff", Needle: "While that decision is pending, stop further repair cycles and dependent chunks.", Diagnostic: "implementation continuation: bounded repair dropped dependent-work stop"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/references/bounded-repair-policy.md", Kind: RequireInSection, Section: "State and handoff", Needle: "The allowance is a maximum, not a target.", Diagnostic: "implementation continuation: bounded repair dropped early completion"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-line/SKILL.md", Kind: RequireInSection, Section: "Retained implementation continuation", Needle: "At initial review or before post-review repairs, including resumed work, read [the bounded repair policy](references/bounded-repair-policy.md).", Diagnostic: "implementation continuation: craft-line dropped the bounded-repair owner"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-implement-spec.md", Kind: RequireInSection, Section: "Build", Needle: "At initial review or before post-review repairs, including resumed work, read [the bounded repair policy](../skills/bench-craft-line/references/bounded-repair-policy.md).", Diagnostic: "implementation continuation: implementation phase dropped bounded repairs"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-review/SKILL.md", Kind: Require, Needle: "Before classifying repairs, read [the bounded repair policy](../bench-craft-line/references/bounded-repair-policy.md).", Diagnostic: "implementation continuation: craft-review dropped bounded repairs"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-review-implementation.md", Kind: RequireInSection, Section: "Review modes", Needle: "Before classifying repairs, read [the bounded repair policy](../skills/bench-craft-line/references/bounded-repair-policy.md).", Diagnostic: "implementation continuation: review phase dropped bounded repairs"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-review-implementation.md", Kind: RequireInSection, Section: "Review modes", Needle: "Here, findings that prevent progression are unresolved blockers; retain optional advice separately under the policy.", Diagnostic: "implementation continuation: review progression counted optional advice"},
}
