package anchors

// ft311PreparationAnchors pin the build phase's prepared-charge authority. The rows cover
// the charge the phase consumes before dispatch, the approval a generated artifact never
// supplies, the revalidation a stale source forces, and the bounds that hold repair triage
// short of a coordinator decision. Every row is a Require row, because these rules are
// sentences the canonical readers must carry, not routes they must avoid.
var ft311PreparationAnchors = []Anchor{
	{Group: AfterImplementSpec, File: ".agents/commands/bench-implement-spec.md", Kind: Require, Needle: "Run `bench preflight build <slug> --charge --ticket <ticket> --base <base> --source-tip <tip>` and read the prepared evidence identity it returns. Retrieve every required source with `bench preflight evidence <id>`, and follow each exact successor command until the stream ends. Verify the fence, dependency completion, and expected source tip before the retained author starts the ticket.", Diagnostic: "prepared build guidance: bench-implement-spec.md dropped charge consumption, approval, supplement contents, or dispatch prerequisites"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-implement-spec.md", Kind: Require, Needle: "Before each ticket, revalidate prepared source identity and required source bytes. Regenerate a charge when either changes.", Diagnostic: "prepared build guidance: bench-implement-spec.md dropped stale-charge revalidation or regeneration"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-delegate/SKILL.md", Kind: Require, Needle: "Use a read-only mid-tier delegate to interpret ambiguous repair evidence. It distinguishes invalid probes, no executed tests, missing coverage, and scope defects only when evidence supports each classification. Missing or contradictory evidence remains unknown. Resolve the harness's bound mid model at medium effort for one iteration. Use high effort only when existing line rules require it.", Diagnostic: "prepared build guidance: craft-delegate dropped bounded mid-tier repair triage"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-delegate/references/delegation-discipline.md", Kind: Require, Needle: "A triage return cites evidence and proposes a bounded repair charge.\n- The coordinator accepts the diagnosis and routes repairs under existing authoring and verification rules.\n- Triage cannot close a finding, expand a fence, waive a probe, or change default tiers.", Diagnostic: "prepared build guidance: delegation discipline lets triage replace coordinator acceptance or independent verification"},

	// The bounded build action rows below pin the five prerequisites the build phase
	// requires together before it acts on prepared evidence. Each row states one
	// prerequisite, so a phase that drops delivery, context, the current binding, approval,
	// or the supplement bites alone. Approval and the supplement keep their own rows,
	// because verified evidence supplies neither one.
	{Group: AfterImplementSpec, File: ".agents/commands/bench-implement-spec.md", Kind: Require, Needle: "Build action requires verified delivery: act only after `bench preflight evidence <id> --verify` reports every stored page and source digest verified.", Diagnostic: "bounded build action: bench-implement-spec.md permits build action without verified delivery"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-implement-spec.md", Kind: Require, Needle: "Build action requires available required context: a retrieval receipt, a terminal cursor, or another consumer's delivery never replaces the required bytes this session holds.", Diagnostic: "bounded build action: bench-implement-spec.md permits build action without available required context"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-implement-spec.md", Kind: Require, Needle: "Build action requires a current-action binding: act only after `bench preflight evidence <id> --check-current` binds the artifact to the current assignment and source pair.", Diagnostic: "bounded build action: bench-implement-spec.md permits build action without a current binding"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-implement-spec.md", Kind: Require, Needle: "Build action requires reviewer approval, which a generated charge, a staged artifact, or a verified artifact never supplies.", Diagnostic: "bounded build action: bench-implement-spec.md permits build action without reviewer approval"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-implement-spec.md", Kind: Require, Needle: "Build action requires the complete task supplement. The supplement names selectors, model, effort, cap, and mutation, and verified evidence never supplies it.", Diagnostic: "bounded build action: bench-implement-spec.md permits build action without the complete task supplement"},
}
