package anchors

import "testing"

// These independent expectations make removal of a ticket-lock obligation fail.
func TestTicketSlicingPasses(t *testing.T) {
	anchorHarness{group: AfterImplementSpec, rules: []anchorRule{
		{file: ".agents/skills/bench-craft-tickets/SKILL.md", section: "Draft the breakdown", needle: "Before ticket lock, run a source-clause pass and an executable-route pass.", want: "ticket slicing: verification passes must precede ticket lock"},
		{file: ".agents/skills/bench-craft-tickets/SKILL.md", section: "Draft the breakdown", needle: "Assign each applicable source clause to a ticket or an explicit scope cut.", want: "ticket slicing: source clauses need a ticket or explicit scope cut"},
		{file: ".agents/skills/bench-craft-tickets/SKILL.md", section: "Draft the breakdown", needle: "Trace each claimed operation through its executable owner, using the [map-discipline proof rules](../bench-craft-spec/references/map-discipline.md#before-the-map-locks).", want: "ticket slicing: executable routes need their owner and canonical proof rules"},
		{file: ".agents/skills/bench-craft-tickets/SKILL.md", section: "Write one file per ticket", needle: "A ticket names every relocation destination in `Writes:`, including destinations for snapshots and registry rows.", want: "ticket slicing: relocation destinations belong in Writes"},
		{file: ".agents/skills/bench-craft-tickets/SKILL.md", section: "Draft the breakdown", needle: "A ticket that creates a seam its sibling tickets consume is its own review chunk, and that chunk stays small. Its chunk review closes before any consumer ticket starts. A seam the implementation introduces counts the same as a seam the spec declares.", want: "ticket slicing: a seam-creating ticket takes its own review chunk and closes review before its consumers"},
		{file: ".agents/skills/bench-craft-tickets/SKILL.md", section: "Write one file per ticket", needle: "Before you lock a `Writes:` line, read [the slicing checks](references/slicing-checks.md), which list every `Writes:` rule that the parser and build preflight enforce.", want: "ticket slicing: craft-tickets must point to the slicing checks"},
		{file: ".agents/skills/bench-craft-tickets/references/slicing-checks.md", section: "Enforced rules", needle: "A `Writes:` entry for an anchored guidance path, or a directory above one, names every anchor registry file that names it, test files included.", want: "ticket slicing: the anchor closure rule is enforced"},
		{file: ".agents/skills/bench-craft-tickets/references/slicing-checks.md", section: "Enforced rules", needle: "The spec's ownership fence equals the union of the ticket `Writes:` paths, less the review pickup and every path under the spec folder or `capture`.", want: "ticket slicing: the fence equals the Writes union"},
		{file: ".agents/skills/bench-craft-tickets/references/slicing-checks.md", section: "Slicing rules", needle: "A lane-check ticket proves its check through the real lane over a composed tree.", want: "ticket slicing: a lane check needs the real lane"},
		{file: ".agents/skills/bench-craft-tickets/references/slicing-checks.md", section: "Slicing rules", needle: "A posture change that reds a fixture helper makes the slicer list every call site of that helper before the map locks.", want: "ticket slicing: a fixture helper posture change lists every call site"},
		{file: ".agents/skills/bench-craft-tickets/references/slicing-checks.md", section: "Slicing rules", needle: "A combined behavior row belongs to the ticket that completes its final consumer.", want: "ticket slicing: a combined row belongs to its final consumer"},
		{file: ".agents/skills/bench-craft-tickets/references/slicing-checks.md", section: "Slicing rules", needle: "A retirement pass gives each sentence that grants the retired behavior its own forbid row and red-capable check.", want: "ticket slicing: each retired grant needs its own forbid row"},
		{file: ".agents/skills/bench-craft-tickets/references/slicing-checks.md", section: "Slicing rules", needle: "A cited verifier row names the exact checks it performed.", want: "ticket slicing: a verifier row names its exact checks"},
		{file: ".agents/skills/bench-craft-tickets/references/slicing-checks.md", section: "Slicing rules", needle: "The slicer runs `bench preflight build <slug>` after each change to a ticket or an acceptance row.", want: "ticket slicing: build preflight reruns after each ticket or acceptance row change"},
		{file: ".agents/skills/bench-craft-tickets/references/slicing-checks.md", section: "Slicing rules", needle: "The spec goes to review, to sign-off, and to its landing only on a green preflight of its current ticket graph.", want: "ticket slicing: review, sign-off, and the landing wait for a green build preflight"},
		{file: ".agents/skills/bench-craft-tickets/references/slicing-checks.md", section: "Slicing rules", needle: "Each acceptance claim names an available producer and an executable check at its ticket checkpoint.", want: "ticket slicing: each claim names its producer and check at its checkpoint"},
		{file: ".agents/skills/bench-craft-tickets/references/slicing-checks.md", section: "Slicing rules", needle: "A ticket that preserves or moves a ref names a check for each of the head, the tip, and the checked-out-ref shapes.", want: "ticket slicing: a ref move checks every ref shape"},
		{file: ".agents/skills/bench-craft-tickets/references/slicing-checks.md", section: "Slicing rules", needle: "A rule for one member of an enumerated family goes on its declaration row, and `Writes:` names the declaration table and its dispatch test.", want: "ticket slicing: a per-member rule fences its family declaration table and dispatch test"},
		{file: ".agents/skills/bench-craft-tickets/references/slicing-checks.md", section: "Slicing rules", needle: "A ticket that adds a second caller of another package's private rule names that package in `Writes:`, so one exported rule serves both callers.", want: "ticket slicing: a second caller of a private rule fences the rule's owner package"},
		{file: ".agents/skills/bench-craft-spec/references/map-discipline.md", section: "Before the map locks", needle: "A spec that adds an invariant check sweeps every input constructor of that check.", want: "map discipline: a new invariant check sweeps its input constructors"},
		{file: ".agents/skills/bench-craft-spec/references/map-discipline.md", section: "Before the map locks", needle: "Each input constructor satisfies the new invariant, or its file joins a ticket `Writes:` line.", want: "map discipline: each input constructor satisfies the invariant or joins Writes"},
		{file: ".agents/skills/bench-craft-spec/references/map-discipline.md", section: "Before the map locks", needle: "A spec that adds or removes a preflight row names every file that asserts the row count or the row list.", want: "map discipline: a preflight row change names every row-count reader"},
		{file: ".agents/skills/bench-craft-spec/references/map-discipline.md", section: "Before the map locks", needle: "A spec that changes the output of a fixture builder names every test that asserts or rewrites that output.", want: "map discipline: a fixture builder change names every output reader"},
		{file: ".agents/skills/bench-craft-spec/references/map-discipline.md", section: "Per row", needle: "The seam cell cites that function as `` `<path>_test.go` (`<Name>`) ``, so `bench coverage --check` and build preflight resolve the name against the tree.", want: "map discipline: an existing test seam cites its function in the resolvable form"},
	}}.check(t)
}
