package anchors

var calibrationAnchors = []Anchor{
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-delegate/references/delegation-discipline.md", Kind: RequireInSection, Section: "Claim schema", Needle: "A done-claim row carries a `status` of `verified`, `claimed`, or `abstained` and a stated confidence as an integer from 0 to 10.", Diagnostic: "calibration: a done-claim row needs its status and stated confidence"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-delegate/references/delegation-discipline.md", Kind: RequireInSection, Section: "Claim schema", Needle: "`verified` means the author ran the named check and returns its red-to-green log, and `claimed` means an assertion with no executed check.", Diagnostic: "calibration: verified and claimed need their evidence definitions"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-delegate/references/delegation-discipline.md", Kind: RequireInSection, Section: "Claim schema", Needle: "A claim carries no free-text field.", Diagnostic: "calibration: a claim must carry no free-text field"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-delegate/references/delegation-discipline.md", Kind: RequireInSection, Section: "Claim schema", Needle: "A delegate that cannot state a confidence returns the row `abstained` with no confidence.", Diagnostic: "calibration: an unstatable confidence needs an abstained row"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-delegate/references/delegation-discipline.md", Kind: RequireInSection, Section: "Claim schema", Needle: "No later probe turns an abstention into a refuted claim.", Diagnostic: "calibration: an abstention must never become a refuted claim"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-delegate/references/delegation-discipline.md", Kind: RequireInSection, Section: "Claim schema", Needle: "The coordinator's probe of the exact tree labels a done-claim row `held` or `refuted`, whatever its status.", Diagnostic: "calibration: the coordinator's tree probe labels each done-claim row"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-delegate/SKILL.md", Kind: RequireInSection, Section: "The charge", Needle: "The charge names the `Claim schema` section of `references/delegation-discipline.md` as the return shape.", Diagnostic: "calibration: the charge must name the claim schema section"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-review/references/finding-discipline.md", Kind: RequireInSection, Section: "What a confidence states", Needle: "A finding carries a stated confidence as an integer from 0 to 10.", Diagnostic: "calibration: a finding needs its stated confidence"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-review/references/finding-discipline.md", Kind: RequireInSection, Section: "What a confidence states", Needle: "The confidence never changes whether a finding blocks.", Diagnostic: "calibration: the confidence must never change whether a finding blocks"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-review/references/finding-discipline.md", Kind: RequireInSection, Section: "What a confidence states", Needle: "`auto-fix` and `ask-user` label a finding `held`, and `no-op` labels it `refuted`.", Diagnostic: "calibration: the dispositions need their label mapping"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-review/references/finding-discipline.md", Kind: RequireInSection, Section: "What a confidence states", Needle: "Optional advice carries no confidence.", Diagnostic: "calibration: optional advice must carry no confidence"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-review/SKILL.md", Kind: RequireInSection, Section: "What a finding must cite", Needle: "A finding also states its confidence as an integer from 0 to 10.", Diagnostic: "calibration: the review skill must point at the finding confidence"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-review-implementation.md", Kind: RequireInSection, Section: "Process", Needle: "Each actionable finding line carries its stated confidence.", Diagnostic: "calibration: the pickup line must carry its stated confidence"},
}
