package anchors

// ft311ReviewDispatchAnchors pin the review phase's native-dispatch authority, the
// prepared evidence that phase consumes, and the triage input contract beside it. The
// Require rows keep each rule present. The Forbid rows keep the retired same-family
// CLI and inline-axis routes out. One diagnostic prefix lets the conformance owner
// enumerate this set without a second registry.
var ft311ReviewDispatchAnchors = []Anchor{
	{Group: AfterImplementSpec, File: ".agents/commands/bench-review-implementation.md", Kind: Require, Needle: "An authorized review dispatches every prepared axis through the native agent surface. It asks no second approval turn inside that authorization. Each axis keeps its own context, its own isolated read-only venue, and its own independent source derivation.", Diagnostic: "FT311 prepared review dispatch: bench-review-implementation.md dropped automatic native axis dispatch, the no-second-approval rule, or per-axis isolation"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-review-implementation.md", Kind: Require, Needle: "Collect the shared evidence once with `bench preflight review <spec> --charge --base <b> --source-tip <t> --full`. Supply the same frozen base that preflight used. The command returns one charge row for each axis. It also returns a `shared_evidence` table with one identity each for diff, consumers, and coverage.", Diagnostic: "FT311 prepared review dispatch: bench-review-implementation.md does not consume the prepared shared evidence; the phase collects the diff, consumers, and coverage a second time"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-review-implementation.md", Kind: Require, Needle: "Take the consumer tables and their citation row from the shared evidence's `consumers` identity. Do not run a second `bench consumers --changed` collection for the same frozen pair.", Diagnostic: "FT311 prepared review dispatch: bench-review-implementation.md walks the blast from a second consumer collection instead of the prepared shared evidence"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-delegate/references/delegation-discipline.md", Kind: Require, Needle: "The CLI owns routine deterministic failure projection. A triage delegate never repeats it.", Diagnostic: "FT311 prepared review dispatch: delegation-discipline.md dropped the CLI's ownership of routine deterministic failure projection"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-delegate/references/delegation-discipline.md", Kind: Require, Needle: "The coordinator gives triage the failed command, the selected checks, the actual execution evidence, the findings, and the frozen source.", Diagnostic: "FT311 prepared review dispatch: delegation-discipline.md dropped the triage input contract of failed command, selected checks, execution evidence, findings, and frozen source"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-review-implementation.md", Kind: Require, Needle: "Collect every axis return before you accept a finding. A missing or failed axis return leaves the review incomplete. It is never a clean finding set.", Diagnostic: "FT311 prepared review dispatch: bench-review-implementation.md lets a missing or failed axis return stand as a clean finding set"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-review-implementation.md", Kind: Require, Needle: "Native availability is a fact of the active session. A compiled harness record is not runtime proof of a native agent surface.", Diagnostic: "FT311 prepared review dispatch: bench-review-implementation.md accepts a compiled harness record as runtime proof of a native surface"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-review-implementation.md", Kind: Require, Needle: "When the native tool is unavailable, or when the reviewer prohibits delegation, preserve the prepared charges and stop dispatch. Then emit a capable-harness handoff. The handoff names the repository, the assignment, the frozen pair, the charge inputs, the destination harness, and that harness's exact native continuation command.", Diagnostic: "FT311 prepared review dispatch: bench-review-implementation.md dropped charge preservation, the dispatch stop, or one named input of the capable-harness handoff"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-review-implementation.md", Kind: Require, Needle: "A historical review and a spec-less review keep their existing preparation entry points under this same native authority rule.", Diagnostic: "FT311 prepared review dispatch: bench-review-implementation.md exempts a historical or spec-less review from the native authority rule"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-review-implementation.md", Kind: Forbid, Needle: "run the same axes inline", Diagnostic: "FT311 prepared review dispatch: bench-review-implementation.md retains the inline-axis fallback"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-delegate/references/cross-harness-reviewers.md", Kind: Require, Needle: "A harness without a native subagent surface takes the capable-harness handoff in `.agents/commands/bench-review-implementation.md`, and it substitutes no same-family CLI.", Diagnostic: "FT311 prepared review dispatch: cross-harness-reviewers.md dropped the capable-harness handoff route for a missing native surface"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-delegate/references/cross-harness-reviewers.md", Kind: Forbid, Needle: "falls back to its own family's CLI", Diagnostic: "FT311 prepared review dispatch: cross-harness-reviewers.md retains the own-family CLI fallback"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-delegate/SKILL.md", Kind: Require, Needle: "Without a native surface, hand off to a capable harness.", Diagnostic: "FT311 prepared review dispatch: craft-delegate dropped the capable-harness handoff route for a missing native surface"},
}
