package anchors

// ft311PreparationAnchors pin the build phase's prepared-charge authority. The rows cover
// the charge the phase consumes before dispatch, the approval a generated artifact never
// supplies, the revalidation a stale source forces, and the bounds that hold repair triage
// short of a coordinator decision. Every row is a Require row, because these rules are
// sentences the canonical readers must carry, not routes they must avoid.
var ft311PreparationAnchors = []Anchor{
	{Group: AfterImplementSpec, File: ".agents/commands/bench-implement-spec.md", Kind: Require, Needle: "After reviewer approval of the selected spec and ticket, run `bench preflight build <slug> --charge --ticket <ticket> --base <base> --source-tip <tip> --full` and retrieve its complete mechanical inputs. Require a complete task-specific supplement. A generated charge or staged artifact does not supply approval. The supplement names selectors, model, effort, cap, and mutation. Verify the fence, dependency completion, and expected source tip before a write delegate starts.", Diagnostic: "prepared build guidance: bench-implement-spec.md dropped charge consumption, approval, supplement contents, or dispatch prerequisites"},
	{Group: AfterImplementSpec, File: ".agents/commands/bench-implement-spec.md", Kind: Require, Needle: "Before delegate dispatch, revalidate prepared source identity and required source bytes. Regenerate a charge when either changes.", Diagnostic: "prepared build guidance: bench-implement-spec.md dropped stale-charge revalidation or regeneration"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-delegate/SKILL.md", Kind: Require, Needle: "Use a read-only mid-tier delegate to interpret ambiguous repair evidence. It distinguishes invalid probes, no executed tests, missing coverage, and scope defects only when evidence supports each classification. Missing or contradictory evidence remains unknown. Resolve the harness's bound mid model at medium effort for one iteration. Use high effort only when existing line rules require it.", Diagnostic: "prepared build guidance: craft-delegate dropped bounded mid-tier repair triage"},
	{Group: AfterImplementSpec, File: ".agents/skills/bench-craft-delegate/references/delegation-discipline.md", Kind: Require, Needle: "A triage return cites evidence and proposes a bounded repair charge.\n- The coordinator accepts the diagnosis and routes repairs under existing authoring and verification rules.\n- Triage cannot close a finding, expand a fence, waive a probe, or change default tiers.", Diagnostic: "prepared build guidance: delegation discipline lets triage replace coordinator acceptance or independent verification"},
}
