package adopt

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"syscall"

	"github.com/gibbonmi/bench/internal/git"
	"github.com/gibbonmi/bench/internal/sanitize"
	"github.com/gibbonmi/bench/internal/usage"
)

const shimMarkerID = "bench-shim v1"

type DoctorEnv struct {
	Home           string
	Path           string
	Shell          string
	NVMDir         string
	ASDFDataDir    string
	FNMDir         string
	VoltaHome      string
	HomebrewPrefix string
}

func currentDoctorEnv() DoctorEnv {
	home, _ := os.UserHomeDir()
	return DoctorEnv{
		Home:           firstNonEmpty(os.Getenv("HOME"), home),
		Path:           os.Getenv("PATH"),
		Shell:          os.Getenv("SHELL"),
		NVMDir:         os.Getenv("NVM_DIR"),
		ASDFDataDir:    os.Getenv("ASDF_DATA_DIR"),
		FNMDir:         os.Getenv("FNM_DIR"),
		VoltaHome:      os.Getenv("VOLTA_HOME"),
		HomebrewPrefix: os.Getenv("HOMEBREW_PREFIX"),
	}
}

func firstNonEmpty(v, fallback string) string {
	if v != "" {
		return v
	}
	return fallback
}

func SelectDoctorDir(env DoctorEnv) (string, bool) {
	for _, dir := range filepath.SplitList(env.Path) {
		if dir == "" || !filepath.IsAbs(dir) {
			continue
		}
		info, err := os.Stat(dir)
		if err != nil || !info.IsDir() || !dirWritable(dir) {
			continue
		}
		if doctorManagerOwned(dir, env) {
			continue
		}
		return dir, false
	}
	fallback := filepath.Join(env.Home, ".local", "bin")
	_, err := os.Stat(fallback)
	return fallback, os.IsNotExist(err)
}

func dirWritable(dir string) bool {
	const writeOK = 2
	return syscall.Access(dir, writeOK) == nil
}

func doctorManagerOwned(dir string, env DoctorEnv) bool {
	home := env.Home
	prefixes := []string{
		firstNonEmpty(env.NVMDir, filepath.Join(home, ".nvm")),
		firstNonEmpty(env.ASDFDataDir, filepath.Join(home, ".asdf")),
		env.FNMDir,
		filepath.Join(home, ".local", "share", "fnm"),
		filepath.Join(home, ".fnm"),
		firstNonEmpty(env.VoltaHome, filepath.Join(home, ".volta")),
		env.HomebrewPrefix,
		"/opt/homebrew",
		"/usr/local",
		"/usr",
		"/bin",
		"/sbin",
		"/opt",
	}
	for _, p := range prefixes {
		if p == "" {
			continue
		}
		if pathUnder(dir, p) {
			return true
		}
	}
	return false
}

func pathUnder(path, prefix string) bool {
	path = filepath.Clean(path)
	prefix = filepath.Clean(prefix)
	return path == prefix || strings.HasPrefix(path, prefix+string(os.PathSeparator))
}

func ShimContent(target string) string {
	quoted := sanitize.ShellQuote(target)
	return strings.Join([]string{
		"#!/usr/bin/env bash",
		"# " + shimMarkerID + " - generated by bench doctor --fix; do not hand-edit",
		"# bench-target: " + target,
		"target=" + quoted,
		`resolve_path() {`,
		`  local p="$1" d t hops=0`,
		`  while [ -L "$p" ]; do`,
		`    hops=$((hops + 1)); [ "$hops" -le 40 ] || return 1`,
		`    d="$(cd -P "$(dirname "$p")" 2>/dev/null && pwd)" || return 1`,
		`    t="$(readlink "$p")" || return 1`,
		`    case "$t" in /*) p="$t" ;; *) p="$d/$t" ;; esac`,
		`  done`,
		`  d="$(cd -P "$(dirname "$p")" 2>/dev/null && pwd)" || return 1`,
		`  printf '%s/%s\n' "$d" "$(basename "$p")"`,
		`}`,
		`root="$(git rev-parse --show-toplevel 2>/dev/null || true)"`,
		`common="$(git rev-parse --path-format=absolute --git-common-dir 2>/dev/null || true)"`,
		`main_root="${common:+${common%/.git}}"`,
		`target_resolved="$(resolve_path "$target" || true)"`,
		`case "${1:-}" in`,
		`  setup|link|init|doctor|unlink)`,
		`    if [ ! -x "$target" ]; then printf 'bench moved - run '\''bench doctor --fix'\'' or reinstall\n' >&2; exit 127; fi`,
		`    exec "$target" "$@"`,
		`    ;;`,
		`esac`,
		`for local_wrapper in "${root:+$root/.bench/bin/bench.sh}" "${main_root:+$main_root/.bench/bin/bench.sh}"; do`,
		`  if [ -n "$local_wrapper" ] && [ -x "$local_wrapper" ]; then`,
		`    local_resolved="$(resolve_path "$local_wrapper" || true)"`,
		`    if [ -n "$local_resolved" ] && [ "$local_resolved" != "$target_resolved" ]; then`,
		`      exec "$local_wrapper" "$@"`,
		`    fi`,
		`  fi`,
		`done`,
		`if [ ! -x "$target" ]; then`,
		`  printf 'bench moved - run '\''bench doctor --fix'\'' or reinstall\n' >&2`,
		"  exit 127",
		"fi",
		`exec "$target" "$@"`,
	}, "\n")
}

func ShimTarget(content string) string {
	for _, line := range strings.Split(content, "\n") {
		if strings.HasPrefix(line, "# bench-target: ") {
			return strings.TrimPrefix(line, "# bench-target: ")
		}
	}
	return ""
}

func shimHasMarker(path string) bool {
	content, err := os.ReadFile(path)
	return err == nil && strings.Contains(string(content), shimMarkerID)
}

func shimTargetFromFile(path string) string {
	content, err := os.ReadFile(path)
	if err != nil {
		return ""
	}
	return ShimTarget(string(content))
}

var doctorGrammar = usage.Grammar{
	Cmd:   "bench doctor",
	Help:  "usage: bench doctor [--fix]",
	Flags: []usage.Flag{{Name: "--fix"}},
}

func Doctor(args []string, stdout, stderr io.Writer, version string) int {
	parsed, line, code := usage.Parse(doctorGrammar, args)
	if line != "" {
		if code == 0 {
			fmt.Fprintln(stdout, line)
		} else {
			fmt.Fprintln(stderr, line)
		}
		return code
	}
	if _, fix := parsed.Flags["--fix"]; fix {
		return doctorFix(stdout, stderr, version)
	}
	return doctorReport(stdout, version)
}

func doctorReport(stdout io.Writer, version string) int {
	env := currentDoctorEnv()
	dir, _ := SelectDoctorDir(env)
	targetPath := filepath.Join(dir, "bench")
	found := ""
	for _, d := range filepath.SplitList(env.Path) {
		if d == "" {
			continue
		}
		p := filepath.Join(d, "bench")
		if info, err := os.Stat(p); err == nil && !info.IsDir() && shimHasMarker(p) {
			found = p
			break
		}
	}

	shimPath := targetPath
	state := "missing"
	if found != "" {
		shimPath = found
		t := shimTargetFromFile(found)
		if t != "" && isExecutable(t) {
			state = "healthy"
		} else {
			state = "stale"
		}
	} else if _, err := os.Lstat(targetPath); err == nil {
		state = "foreign"
	}

	fmt.Fprintln(stdout, "bench doctor - shim health")
	rc := 1
	switch state {
	case "healthy":
		fmt.Fprintf(stdout, "  ok: healthy bench shim at %s\n", shimPath)
		rc = 0
	case "stale":
		fmt.Fprintf(stdout, "  stale: shim at %s points to a missing target (version-manager move?)\n", shimPath)
	case "foreign":
		fmt.Fprintf(stdout, "  foreign: %s exists but is not a bench shim (no marker)\n", shimPath)
	case "missing":
		fmt.Fprintln(stdout, "  missing: no bench shim on a stable PATH dir")
	}
	printSkewWarning(stdout, version)
	if reportPrePush(stdout) {
		rc = 1
	}
	if reportDoctorRows(stdout) {
		rc = 1
	}
	fmt.Fprintln(stdout, "  fix:    bench doctor --fix")
	fmt.Fprintf(stdout, "  remove: npm uninstall -g redbench && rm -f %q\n", shimPath)
	return rc
}

// reportPrePush renders the pre-push backstop row when doctor runs inside a git worktree,
// and returns whether the row is red. git does not clone hooks, so a fresh clone silently
// drops the default-branch backstop; this catches that the next time doctor runs. A stale
// bench-managed hook is repaired by bench doctor --fix; an absent, foreign, or diverted hook
// is left untouched and points to bench link instead. In the kit source checkout bench link
// is not a remedy at all, so an absent hook names bench doctor --fix, which installs it
// there. A red row makes doctor exit 1 even when the shim is healthy.
func reportPrePush(stdout io.Writer) bool {
	root, err := git.Root()
	if err != nil {
		return false // not in a git worktree — no backstop to verify
	}
	health := InspectPrePush(root)
	switch health.State {
	case PrePushManaged:
		if health.Currency == PrePushStale {
			fmt.Fprintf(stdout, "  stale: bench-managed pre-push at %s no longer matches the current hook - run bench doctor --fix\n", health.Path)
			return true
		}
		fmt.Fprintf(stdout, "  ok: bench-managed pre-push at %s (branch %s; provenance %s)\n", health.Path, health.Branch, health.Provenance)
		return false
	case PrePushForeign:
		fmt.Fprintf(stdout, "  pre-push: %s is present but not bench-managed (no marker) - run bench link\n", health.Path)
	case PrePushDiverted:
		fmt.Fprintf(stdout, "  pre-push: diverted by core.hooksPath to %s with no bench-managed hook - run bench link\n", health.Path)
	default: // PrePushAbsent
		remedy := "run bench link"
		if KitSourceCheckout(root) {
			remedy = "run bench doctor --fix"
		}
		fmt.Fprintf(stdout, "  pre-push: absent at %s - a fresh clone drops it (git does not clone hooks); %s\n", health.Path, remedy)
	}
	return true
}

// KitSourceCheckout reports whether root is the kit's own source tree. The kit repo is
// where the managed AGENTS.md block and the bin/bench.sh launcher are authored, so it
// never carries the consumer-side copy of either, and a row that sent its reader to bench
// link would name a remedy that breaks the shim route and the land route. A consumer repo
// never satisfies the predicate, because its kit resolves to a package or cache directory
// outside the repository. Both paths resolve through symlinks first, so a repository
// reached by one spelling and a BENCH_KIT set to another still match.
func KitSourceCheckout(root string) bool {
	kit := kitDir()
	if root == "" || kit == "" {
		return false
	}
	return resolvedPath(root) == resolvedPath(kit)
}

func resolvedPath(path string) string {
	if resolved, err := filepath.EvalSymlinks(path); err == nil {
		return resolved
	}
	return filepath.Clean(path)
}

func printSkewWarning(stdout io.Writer, version string) {
	root, err := git.Root()
	if err != nil {
		return
	}
	manifestPath := filepath.Join(root, ".bench", "link-manifest.tsv")
	if _, err := os.Stat(manifestPath); err != nil {
		return
	}
	m, err := ReadManifest(manifestPath)
	if err != nil {
		return
	}
	if m.KitVersion == "" {
		fmt.Fprintln(stdout, "  warning: linked kit version unknown (run bench link to stamp .bench/link-manifest.tsv)")
		return
	}
	if m.KitVersion != version {
		fmt.Fprintf(stdout, "  warning: version skew: linked kit %s, running kit %s\n", m.KitVersion, version)
	}
}

func doctorFix(stdout, stderr io.Writer, version string) int {
	env := currentDoctorEnv()
	dir, create := SelectDoctorDir(env)
	if create {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			fmt.Fprintf(stderr, "  error: could not create %s\n", dir)
			return 1
		}
		fmt.Fprintf(stdout, "  created directory %s\n", dir)
	}
	target := resolvedWrapper()
	targetPath := filepath.Join(dir, "bench")
	content := ShimContent(target) + "\n"
	if _, err := os.Lstat(targetPath); err == nil {
		if shimHasMarker(targetPath) {
			existing, _ := os.ReadFile(targetPath)
			if string(existing) == content {
				fmt.Fprintf(stdout, "  ok: shim already current at %s (no change)\n", targetPath)
				doctorPathNotice(stdout, env, dir)
				if publishBrokerManifest(stdout, stderr, version) != 0 {
					return 1
				}
				return repairStalePrePush(stdout, stderr)
			}
		} else {
			fmt.Fprintf(stderr, "  refusing: %s exists and is not a bench shim (no marker); left unchanged\n", targetPath)
			return 1
		}
	}
	tmp, err := os.CreateTemp(dir, ".bench-shim.")
	if err != nil {
		fmt.Fprintf(stderr, "  error: cannot write in %s\n", dir)
		return 1
	}
	tmpName := tmp.Name()
	if _, err := tmp.WriteString(content); err != nil {
		_ = tmp.Close()
		_ = os.Remove(tmpName)
		fmt.Fprintf(stderr, "  error: cannot write in %s\n", dir)
		return 1
	}
	if err := tmp.Close(); err != nil {
		_ = os.Remove(tmpName)
		fmt.Fprintf(stderr, "  error: cannot write in %s\n", dir)
		return 1
	}
	if err := os.Chmod(tmpName, 0o755); err != nil {
		_ = os.Remove(tmpName)
		fmt.Fprintf(stderr, "  error: cannot write in %s\n", dir)
		return 1
	}
	if err := os.Rename(tmpName, targetPath); err != nil {
		_ = os.Remove(tmpName)
		fmt.Fprintf(stderr, "  error: cannot write in %s\n", dir)
		return 1
	}
	fmt.Fprintf(stdout, "  wrote shim %s (exec -> %s)\n", targetPath, target)
	doctorPathNotice(stdout, env, dir)
	if publishBrokerManifest(stdout, stderr, version) != 0 {
		return 1
	}
	return repairStalePrePush(stdout, stderr)
}

// publishBrokerManifest publishes the promotion-broker manifest as part of the fix,
// so the install and repair owner ships the broker and its binding together. The
// wrapper's `worktree land` route trusts only this binding.
func publishBrokerManifest(stdout, stderr io.Writer, version string) int {
	path, broker, err := WriteBrokerManifest(version)
	if err != nil {
		fmt.Fprintf(stderr, "  error: %v\n", err)
		return 1
	}
	fmt.Fprintf(stdout, "  wrote broker manifest %s (broker %s)\n", path, broker)
	return 0
}

func repairStalePrePush(stdout, stderr io.Writer) int {
	root, err := git.Root()
	if err != nil {
		return 0
	}
	health := InspectPrePush(root)
	switch health.State {
	case PrePushManaged:
		if health.Currency == PrePushCurrent {
			fmt.Fprintf(stdout, "  ok: pre-push already current at %s (no change)\n", health.Path)
			return 0
		}
		if err := installGitHook(root, stderr); err != nil {
			return 1
		}
		if err := restorePrePushExecuteMode(health.Path); err != nil {
			fmt.Fprintf(stderr, "  error: cannot restore executable mode on pre-push at %s\n", health.Path)
			return 1
		}
		if InspectPrePush(root).Currency != PrePushCurrent {
			fmt.Fprintf(stderr, "  error: pre-push at %s remains stale after repair\n", health.Path)
			return 1
		}
		fmt.Fprintf(stdout, "  repaired stale pre-push at %s\n", health.Path)
	case PrePushForeign:
		fmt.Fprintf(stderr, "  refusing: %s exists and is not a bench-managed pre-push; left unchanged\n", health.Path)
		return 1
	case PrePushAbsent:
		// Only in the kit source checkout, where the absent-hook row names this fix because
		// bench link is not a remedy there. Elsewhere an absent hook stays bench link's, so
		// the fix does not silently take over a route the link transaction owns.
		if !KitSourceCheckout(root) {
			return 0
		}
		if err := installGitHook(root, stderr); err != nil {
			return 1
		}
		fmt.Fprintf(stdout, "  installed pre-push at %s\n", health.Path)
	}
	return 0
}

// restorePrePushExecuteMode adds execute bits to a hook that was already present when the
// repair rewrote it. Writing over an existing file leaves its mode untouched, and git
// skips a pre-push it cannot execute. The other permission bits are the operator's, so
// they stay.
func restorePrePushExecuteMode(path string) error {
	if isExecutable(path) {
		return nil
	}
	info, err := os.Stat(path)
	if err != nil {
		return err
	}
	return os.Chmod(path, info.Mode().Perm()|0o111)
}

func resolvedWrapper() string {
	if p := os.Getenv("BENCH_WRAPPER"); p != "" {
		return p
	}
	if p, err := os.Executable(); err == nil {
		if real, err := filepath.EvalSymlinks(p); err == nil {
			return real
		}
		return p
	}
	if len(os.Args) > 0 {
		return os.Args[0]
	}
	return "bench"
}

func isExecutable(path string) bool {
	info, err := os.Stat(path)
	return err == nil && !info.IsDir() && info.Mode().Perm()&0o111 != 0
}

func doctorPathNotice(stdout io.Writer, env DoctorEnv, dir string) {
	for _, p := range filepath.SplitList(env.Path) {
		if p == dir {
			return
		}
	}
	fmt.Fprintf(stdout, "  note: %s is not on PATH - add it, then restart your shell:\n", dir)
	switch filepath.Base(firstNonEmpty(env.Shell, "/bin/sh")) {
	case "fish":
		fmt.Fprintf(stdout, "    fish_add_path %s\n", dir)
	default:
		fmt.Fprintf(stdout, "    export PATH=\"%s:$PATH\"\n", dir)
	}
}

func hostOSArch() string {
	return runtime.GOOS + "/" + runtime.GOARCH
}
